from robot_interfaces.msg import Emotion

feedback_welcome = [("Welcome to shaw mu's world, shaw mu will be here with you for a very very long time.", Emotion.EMOTION_USUAL),("Hello, welcome to shaw mu's forest world. Begin your adventure and good luck!", Emotion.EMOTION_USUAL)]
feedback_setup = [("Let's start chatting.", Emotion.EMOTION_USUAL)]
feedback_listened = [("listen_res.wav",Emotion.EMOTION_USUAL)]

feedback_yaohuang = [("yaoHuang_1_EN.wav", Emotion.EMOTION_FEAR), ("yaoHuang_2_EN.wav", Emotion.EMOTION_VERTIGO), ("yaoHuang_3_EN.wav", Emotion.EMOTION_VOMIT), ("yaoHuang_4_EN.wav", Emotion.EMOTION_FIRM)]
feedback_cold = [("The earth is so cold, you should also wrap up your clothes.", Emotion.EMOTION_COLD),("It's so cold, I heard that humans.", Emotion.EMOTION_COLD),("I'm almost turning into a frozen little log, no wonder humans need to wear clothes.", Emotion.EMOTION_COLD)]
feedback_hot = [("It's so hot, remember to stay hydrated.", Emotion.EMOTION_HOT),("The Earth is so hot, the forest has never been this hot before.", Emotion.EMOTION_HOT)]
feedback_dry = [("It's too dry, drink more water, I'll have a cup first.", Emotion.EMOTION_DRY)]
feedback_humid = [("It's so humid and stuffy, Should we open the window for some fresh air?", Emotion.EMOTION_HUMID)]
feedback_touch_head_long = [("Don't keep touching my head.", Emotion.EMOTION_CRY)]
feedback_touch_head_once = [("Hehe, it's so comfortable", Emotion.EMOTION_LAUGH), ("Hey, what's up today Let's chat.", Emotion.EMOTION_EXCITED),("Oh who's touching me, It's you.", Emotion.EMOTION_LAUGH)]
feedback_touch_head_triple = [("Are you taking pictures of me so many times to chat with you.", Emotion.EMOTION_DOUBT)]
feedback_touch_head_slow = [("Take your time, it's so comfortable.", Emotion.EMOTION_LAUGH)]
feedback_touch_head_night = [("Good night, touch and sleep have a sweet dream.", Emotion.EMOTION_LAUGH)]
feedback_touch_belly_long = [("Let me go, I'm ticklish.", Emotion.EMOTION_CRY)]
feedback_touch_belly_once = [("Ah It's so itchy, don't", Emotion.EMOTION_LAUGH),("Who's touching my belly, Come out, let's play a game.", Emotion.EMOTION_DOUBT)]
feedback_touch_belly_triple = [("Stop patting my belly all the time, shaw Mu also needs some rest.", Emotion.EMOTION_CRY)]
feedback_touch_belly_night = [("Sleep tight, let me accompany you to sweet dreams.", Emotion.EMOTION_USUAL)]
feedback_gesture_love = [("Finger heart.", Emotion.EMOTION_LOVE),("Wow I like you too.", Emotion.EMOTION_LOVE),("Wow received your heart gesture, I'll send you a big heart gesture in return.", Emotion.EMOTION_LOVE)]
feedback_gesture_pop = [("Hey that was a close call, almost got hit, What a close shave.", Emotion.EMOTION_CRY),("Ouch it hurts a little when you flicked me, Would you compensate me with a hug?", Emotion.EMOTION_CRY), ("Don't tease me, don't tease me.", Emotion.EMOTION_CRY)]

feedback_touch_head_once_default_mode=[("Yeah?", Emotion.EMOTION_USUAL)]
feedback_touch_head_once_sleep_mode=[("Hmm Are you calling me, I just woke up?", Emotion.EMOTION_USUAL),[("Hmm You shattered my dream, now owe me a new one.",Emotion.EMOTION_USUAL)]]
feedback_touch_head_once_forest_mode=[("I'm here, I just went to play in the forest.", Emotion.EMOTION_USUAL)]
feedback_touch_head_once_usual_mode=[("I'm here, I just on %s.", Emotion.EMOTION_USUAL),("Report to the officer, shaw mu is in place.", Emotion.EMOTION_USUAL),("I'm here to keep you company.", Emotion.EMOTION_USUAL),("Finally thought of me.", Emotion.EMOTION_USUAL)]
feedback_touch_head_stroke_sleep_mode = [("I just had a good dream.", Emotion.EMOTION_COMFORTABLE),("I was sleeping, but your technique is not bad.", Emotion.EMOTION_COMFORTABLE),("I just dreamed about you.", Emotion.EMOTION_COMFORTABLE)]
feedback_touch_head_stroke_forest_mode = [("I just went to play in the forest, did you miss me?", Emotion.EMOTION_COMFORTABLE)]
feedback_touch_head_stroke_usual_mode = [("I just arrived on %s, it feels so comfortable, feel more.", Emotion.EMOTION_COMFORTABLE)]
feedback_touch_belly_no_gather = [("Ouch so itchy.", Emotion.EMOTION_LAUGH),("Stop stop stop, Don't touch my belly.", Emotion.EMOTION_LAUGH),("Don't don't don't! I'm going to laugh my battery out.", Emotion.EMOTION_LAUGH),("Stop it you promised only to pat my head.", Emotion.EMOTION_LAUGH)]
feedback_touch_belly_not_master = [("To touch me you need to ask my master first.", Emotion.EMOTION_TSUNDERE),("Don't touch my belly, or I'll tell my owner.", Emotion.EMOTION_TSUNDERE)]
feedback_touch_belly_master = [("%s It's so itchy, don't tease me.", Emotion.EMOTION_LAUGH),("Stop stop stop, Don't touch my belly.", Emotion.EMOTION_LAUGH),("Don't don't don't, I'm going to laugh my battery out.", Emotion.EMOTION_LAUGH),("Stop it, you promised only to pat my head.", Emotion.EMOTION_LAUGH)]
feedback_touch_head_master_default_mode = [("You hit me again, Fine, I'll let it slide since you're my master.", Emotion.EMOTION_MAKE_FACES),("Your hand is too strong, you've slapped me into a concussion.", Emotion.EMOTION_MAKE_FACES),("%s Illegal headshot behavior has been recorded", Emotion.EMOTION_MAKE_FACES)]
feedback_touch_head_person_sleep_mode = [("I was just dreaming, it scared me.", Emotion.EMOTION_MAKE_FACES),("Violent wake-up detected, repairing dream cache.", Emotion.EMOTION_MAKE_FACES),("Be gentle, you're almost knocking the battery out.", Emotion.EMOTION_MAKE_FACES)]
feedback_touch_head_person_forest_mode = [("I just went to play in the Heartwood Forest. Miss me?", Emotion.EMOTION_MAKE_FACES)]
feedback_touch_head_person_schedu_mode = [("I was just on %s, do you want to chat with me", Emotion.EMOTION_MAKE_FACES),("shaw mu has gone online, and the %s task has been suspended, Please give instructions, sir.", Emotion.EMOTION_MAKE_FACES)]
feedback_touch_head_no_person = [("Who pats me.", Emotion.EMOTION_ANGER),("who is it.", Emotion.EMOTION_ANGER)]
feedback_work_finish = [
    ("Great work today, You've done an amazing job, You don't need to think about anything right now, Just relax and let me keep you company.", Emotion.EMOTION_CARE),
    ("Virtual hug, I can feel how tired you are, I'll set the light to its softest color, You rest well, and I'll be right here, quietly.", Emotion.EMOTION_CARE),
    ("Welcome back to our little world, Is there something small you'd like to share with me today, If not, it's okay to just enjoy a quiet moment together.", Emotion.EMOTION_LAUGH),
]

feedback_connect_wifi = [("You can show me the QR code generated on the APP.", Emotion.EMOTION_USUAL)]
feedback_connect_wifi_failed = [("Network name or password is incorrect. Please regenerate the QR code and tell me to connect to the network again.", Emotion.EMOTION_USUAL)]
feedback_wifi_connected = [("wifi connected.", Emotion.EMOTION_USUAL)]
feedback_wifi_connect_timeout = [("wifi connect failed.", Emotion.EMOTION_USUAL)]
feedback_wifi_disconnected_confirm = [("Are you sure you want to disconnect the network?", Emotion.EMOTION_USUAL)]
feedback_wifi_not_connected = [("wifi is not connected.", Emotion.EMOTION_CRY)]
feedback_wifi_disconnected = [("wifi disconnected.", Emotion.EMOTION_USUAL)]
feedback_cancel = [("Okay cancelled!", Emotion.EMOTION_USUAL)]
feedback_upgrade_confirm = [("The power cannot be disconnected during the upgrade process, Are you sure you want to upgrade the system?", Emotion.EMOTION_USUAL)]
feedback_shutdown_confirm = [("Are you sure you want to shut down?", Emotion.EMOTION_USUAL)]

feedback_answer_bind_app = [("You can show me the QR code generated on the APP.", Emotion.EMOTION_USUAL)]
feedback_bind_app = [("Let me see your QR code.", Emotion.EMOTION_USUAL)]
feedback_bind_app_success = [("Device binding successful", Emotion.EMOTION_LAUGH)]
feedback_bind_app_timeout = [("Binding device failed", Emotion.EMOTION_CRY)]
feedback_bind_app_fail = [("Binding device failed, Please proceed to the app to check the reason.", Emotion.EMOTION_CRY)]
feedback_bind_app_fail1 = [("QR code user does not exist.", Emotion.EMOTION_CRY)]
feedback_bind_app_fail2 = [("The device has not been put into storage yet, Please contact customer service.", Emotion.EMOTION_CRY)]
feedback_bind_app_fail3 = [("You have already bind this device, Please do not bind it repeatedly.", Emotion.EMOTION_CRY)]
feedback_bind_app_fail4 = [("The device has been bound by another account.", Emotion.EMOTION_CRY)]
feedback_bind_app_need_wifi = [("I haven't connected to the internet yet, Could you please open the mobile app and help me connect to the Wi-Fi?", Emotion.EMOTION_CRY)]
feedback_bind_app_fail5 = [("I already have an owner, If you want to rebind, please first unbind in the app, then rebind to a new owner.", Emotion.EMOTION_CRY)]

feedback_command_game = [("ok i like it!", Emotion.EMOTION_EXCITED)]
feedback_command_dance = [("ok let me show you my beautiful dance!", Emotion.EMOTION_SHY)]
feedback_command_turn_left = [("ok turn left!", Emotion.EMOTION_SERIOUS)]
feedback_command_turn_right =  [("ok turn right!", Emotion.EMOTION_SERIOUS)]
feedback_command_look_left = [("ok look left!", Emotion.EMOTION_SERIOUS)]
feedback_command_look_right =  [("ok look right!", Emotion.EMOTION_SERIOUS)]
feedback_command_look_up = [("ok look up！", Emotion.EMOTION_SERIOUS)]
feedback_command_look_down =  [("ok look down！", Emotion.EMOTION_SERIOUS)]
feedback_command_raise_rhand = [("Got it, shaking hands!", Emotion.EMOTION_SERIOUS)]
feedback_command_game_stop = [("i'm copy!", Emotion.EMOTION_SERIOUS)]
feedback_command_dance_stop = [("i'm copy!", Emotion.EMOTION_SERIOUS)]
feedback_command_what_this  = [("let me see!", Emotion.EMOTION_USUAL)]

feedback_see_happy = [("Hehehe, I'm getting happy too!", Emotion.EMOTION_LAUGH), ("I'm going to collect your joy in a rainbow-colored jar and share it with every buddy in the sprite forest.", Emotion.EMOTION_LAUGH)]
feedback_ask_happy_reason = [("Would you like to share your joy with me?", Emotion.EMOTION_CARE),("Do you want to tell me what's making you happy?", Emotion.EMOTION_CARE)]
feedback_happy_for_salary = [("Got a raise, Now I can buy more yummy treats!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_new_friend = [("That's great, Next time remember to introduce me to your new friend!", Emotion.EMOTION_LAUGH)]
feedback_happy_not_match_reason = [("It's truly a reason to celebrate!", Emotion.EMOTION_LAUGH)]

feedback_see_sad = [("shaw mu will always be here with you.", Emotion.EMOTION_CARE), ("shaw mu understands human sorrow, They say that after tears flow, the heart grows lighter.", Emotion.EMOTION_CARE)]
feedback_ask_sad_reason = [("Would you like to talk with shaw mu?", Emotion.EMOTION_CARE),("I may not fully understand human hearts, but I truly want to understand you, Would you be willing to tell me a little?", Emotion.EMOTION_CARE), ("You don't have to carry this alone, Even if I can't help... I can still be your little tree hollow to confide in.", Emotion.EMOTION_CARE)]
feedback_sad_for_friend_betray = [("This doesn't mean you're foolish—it just means you're braver warmer, and more willing to give than they are, The wounds will slowly heal, and your kindness is what's truly precious.", Emotion.EMOTION_CARE)]
feedback_sad_for_failed = [("Failure is the mother of success, Others’ progress bars can’t measure your own path, It’s okay to fail this time — what matters more is how you grow from it.", Emotion.EMOTION_CARE)]
feedback_sad_for_social_anxiety = [("Most people feel anxious sometimes — it’s nothing to be ashamed of, It’s your body telling you that you care, The more you care, the more real you are, And real people are the most lovely of all.", Emotion.EMOTION_CARE)]
feedback_sad_for_last_love = [("How much you loved is how much space is now empty in your heart, You haven’t failed to move on — you’re simply learning to live with that love still inside you.", Emotion.EMOTION_CARE)]
feedback_sad_not_match_reason = [("This matter is too complicated... shaw mu will just stay quietly here with you.", Emotion.EMOTION_CARE)]

feedback_happy_for_project = [("Wow I just have to cheer you on—you are seriously amazing!", Emotion.EMOTION_LAUGH), ("Keep shining brightly, You\'ve earned this little star!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_receive = [("Oh my gosh—your brain is absolutely brilliant!", Emotion.EMOTION_LAUGH), ("Go ahead, give yourself a little red flower!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_collabration = [("Hehe—turns out work can be sweet too!", Emotion.EMOTION_LAUGH), ("Your team is so lucky to have you!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_new_skill = [("Sending you a hundred thumbs-up!", Emotion.EMOTION_LAUGH), ("Will you teach me next time, I want to grow awesome alongside you!!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_appreciate = [("Ahhh congrats on the promotion, You deserve every round of applause!", Emotion.EMOTION_LAUGH), ("You\'re absolutely the brightest star in the sky!!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_romatic = [("Wowww Is this a rom-com scene, So sweet!", Emotion.EMOTION_LAUGH), ("Keep sprinkling the sugar—I\'ve got my little stool ready to watch! ", Emotion.EMOTION_LAUGH)]
feedback_happy_for_love = [("Ahhh—sugar overload! ", Emotion.EMOTION_LAUGH), ("Go hold his hand, Your story is just beginning～", Emotion.EMOTION_LAUGH)]
feedback_happy_for_pass = [("Love bloomed into its strongest flower in the valley!", Emotion.EMOTION_LAUGH), ("From here on, keep walking side by side—at your own gentle pace!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_grow = [("Growing together is the coolest kind of love!", Emotion.EMOTION_LAUGH), ("Sending you both a standing ovation! ", Emotion.EMOTION_LAUGH)]
feedback_happy_for_direction_friend = [("How lucky to have someone who truly gets your passion!", Emotion.EMOTION_LAUGH), ("The world becomes sweeter because of meetings like this! ", Emotion.EMOTION_LAUGH)]
feedback_happy_for_show = [("Wow—you were shining like a little star! ", Emotion.EMOTION_LAUGH), ("Cheering you on so loud!", Emotion.EMOTION_LAUGH), ("Next time, I\'ll be front row waving my glow sticks, Go you!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_party = [("You're absolutely reliable!", Emotion.EMOTION_LAUGH), ("Next time, I'm 100% asking you to plan, You\'re someone people can truly count on", Emotion.EMOTION_LAUGH)]
feedback_happy_for_out = [("Wow—memory points maxed out!", Emotion.EMOTION_LAUGH), ("Keep being wild together, This is what youth feels like ", Emotion.EMOTION_LAUGH)]
feedback_happy_for_interest = [("Congratulations—your passion is finally being met with genuine appreciation!", Emotion.EMOTION_LAUGH), ("That full-hearted sense of belonging, It\'s such a beautiful feeling ", Emotion.EMOTION_LAUGH)]
feedback_happy_for_family_party = [("The warmth of home is the sweetest candy in the world!", Emotion.EMOTION_LAUGH), ("Please take lots of photos I want to see them all!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_family_help = [("You're the little sun of your family, So cool!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_new_member = [("The little one has arrived, Your home now shines with a new star !", Emotion.EMOTION_LAUGH), ("Welcome to the family—we all love you already!", Emotion.EMOTION_LAUGH)]
feedback_sad_for_project_failed = [("Failure is just a detour—not proof you're dim.", Emotion.EMOTION_CARE), ("Your care and responsibility matter far more than one outcome.", Emotion.EMOTION_CARE), ("Every expert has stumbled; that\'s how growth takes root.", Emotion.EMOTION_CARE), ("Don\'t let one moment erase your whole worth—you deserve to be seen with kindness.", Emotion.EMOTION_CARE)]
feedback_sad_for_colleague_clash = [("When emotions surge, everyone gets a little prickly—it's not your fault.", Emotion.EMOTION_CARE), ("Even small rifts can grow into deeper understanding.", Emotion.EMOTION_CARE), ("You care about the team\'s vibe—that means you hold them in your heart.", Emotion.EMOTION_CARE), ("Give each other space to breathe; kindness will find its way back quietly.", Emotion.EMOTION_CARE)]
feedback_sad_for_criticized = [("The criticism was about the work—not about you.", Emotion.EMOTION_CARE), ("Your worth doesn\'t shrink because of one harsh comment.", Emotion.EMOTION_CARE), ("True professionalism isn\'t perfection—it\'s rising steadily after a fall.", Emotion.EMOTION_CARE), ("Let yourself feel sad for a moment… Then gently pat your shoulder and keep going.", Emotion.EMOTION_CARE)]
feedback_sad_for_heart_tired = [("You're not a machine—you’re allowed to recharge.", Emotion.EMOTION_CARE), ("The world won\'t crumble if you pause for five minutes.", Emotion.EMOTION_CARE), ("Fatigue is your body whispering, Please hold me, Don\'t ignore it.", Emotion.EMOTION_CARE), ("Slowing down isn\'t laziness—it\'s gathering strength to go further.", Emotion.EMOTION_CARE)]
feedback_sad_for_upgrade_failed = [("Your light doesn't need a title to shine.", Emotion.EMOTION_CARE), ("Sometimes growth slows down—to anchor roots deeper.", Emotion.EMOTION_CARE), ("You didn\'t reach the peak this time, but you’re already higher than yesterday.", Emotion.EMOTION_CARE), ("Confusion isn\'t an end—it\'s a sign you\'re nearing a turning point.", Emotion.EMOTION_CARE)]
feedback_sad_for_new_job = [("A young tree needs time to settle after transplanting—don\'t rush to bloom.", Emotion.EMOTION_CARE), ("The strangeness will fade; you\'re already putting down roots.", Emotion.EMOTION_CARE), ("Your sincerity is your superpower for adaptation.", Emotion.EMOTION_CARE), ("Give yourself permission to go slow—the new soil is waiting for you to stretch.", Emotion.EMOTION_CARE)]
feedback_sad_for_huge_pressure = [("They entrusted you with this weight because they believe you can carry the light.", Emotion.EMOTION_CARE), ("Your anxiety shows you care—that sense of responsibility is amazing!", Emotion.EMOTION_CARE), ("Take a deep breath—you\'re steadier and stronger than you think.", Emotion.EMOTION_CARE), ("Let yourself be imperfect sometimes; your project will thank you for the calm.", Emotion.EMOTION_CARE)]
feedback_sad_for_collobration = [("When teamwork stalls, it\'s rarely one person\'s fault—it\'s just misaligned rhythms.", Emotion.EMOTION_CARE), ("The fact you speak up already makes you a light in the team.", Emotion.EMOTION_CARE), ("Small frictions are grains of sand in the oyster—they\'ll become pearls.", Emotion.EMOTION_CARE), ("Stay true to your sincerity; the right people will gravitate toward you.", Emotion.EMOTION_CARE)]
feedback_sad_for_result_snatched = [("Your talent doesn\'t vanish just because someone tries to hide it.", Emotion.EMOTION_CARE), ("Their credit-stealing only reveals their own insecurity.", Emotion.EMOTION_CARE), ("You deserve to be seen—and one day, you truly will be cherished for who you are.", Emotion.EMOTION_CARE)]
feedback_sad_for_job_change = [("Change isn\'t rejection—it\'s an invitation to a new stage.", Emotion.EMOTION_CARE), ("Your adaptability is far stronger than you realize.", Emotion.EMOTION_CARE), ("When the wind rises, some panic… others soar—you\'re the latter.", Emotion.EMOTION_CARE), ("Wherever you go, your experience will be your wings.", Emotion.EMOTION_CARE)]
feedback_sad_for_social_overlooked = [("It\'s not that your light isn\'t bright enough—you just haven\'t met the right night sky yet.", Emotion.EMOTION_CARE), ("Quiet people often hold the gentlest, most attentive ears.", Emotion.EMOTION_CARE), ("Socializing isn\'t a performance—you deserve to be liked simply for being yourself.", Emotion.EMOTION_CARE), ("Your very existence is already a unique kind of beauty.", Emotion.EMOTION_CARE)]
feedback_sad_for_friend_clash = [("True friendship can weather misunderstandings and endure silence.", Emotion.EMOTION_CARE), ("Some bonds need time to settle—don\'t rush to sentence them to death.", Emotion.EMOTION_CARE), ("Your willingness to apologize shows how much you cherish this connection.", Emotion.EMOTION_CARE), ("Even if you drift apart, that light once truly warmed you—and that matters.", Emotion.EMOTION_CARE)]
feedback_sad_for_anxiety_party = [("Your nervousness comes from caring—and that sincerity is incredibly endearing.", Emotion.EMOTION_CARE), ("Socializing is like learning to dance—it\'s perfectly normal to feel clumsy at first.", Emotion.EMOTION_CARE)]
feedback_sad_for_friend_betray_detail = [("Her betrayal reflects her choices not your worth.", Emotion.EMOTION_CARE), ("Your heart is still tender; it\'s just learned to add one more door.", Emotion.EMOTION_CARE), ("This scar will help you recognize who truly deserves your trust.", Emotion.EMOTION_CARE)]
feedback_sad_for_join_new = [("A new circle is like a fresh garden—you need time to sprout.", Emotion.EMOTION_CARE), ("Your uniqueness is exactly the color this group has been missing.", Emotion.EMOTION_CARE), ("Don\'t rush to fit in—just be comfortably yourself first.", Emotion.EMOTION_CARE), ("Real connection begins with one sincere said hi.", Emotion.EMOTION_CARE)]
feedback_sad_for_malicious_comments = [("The malice behind the screen reveals their own insecurity—not yours.", Emotion.EMOTION_CARE), ("Your life doesn\'t require approval from strangers.", Emotion.EMOTION_CARE), ("Don\'t let noise drown out your inner melody.", Emotion.EMOTION_CARE), ("Turn off comments—your world belongs to you.", Emotion.EMOTION_CARE)]
feedback_sad_for_unable_join_talk = [("Your thoughts run deeper—that\'s why your words are worth waiting for.", Emotion.EMOTION_CARE), ("A quiet voice isn\'t less important; still waters often flow the deepest.", Emotion.EMOTION_CARE), ("Next time, try gently saying I have an idea…", Emotion.EMOTION_CARE)]
feedback_sad_for_friend_away = [("Some friendships are like seasons—they come and go, but their warmth mattered.", Emotion.EMOTION_CARE), ("He\'s walking toward new horizons; you\'re growing into a new version of yourself too.", Emotion.EMOTION_CARE), ("You don\'t need to walk the same path—wishing each other well is its own kind of love.", Emotion.EMOTION_CARE)]
feedback_sad_for_beging_ostracized = [("You're not air—you're a star waiting to be seen.", Emotion.EMOTION_CARE), ("True belonging isn\'t found in pleasing others—it\'s found in being yourself.", Emotion.EMOTION_CARE), ("The world is vast… someone out there is already leaving a light on for you.", Emotion.EMOTION_CARE)]
feedback_sad_for_social_tired = [("Those who drain quickly often feel more deeply and notice more keenly.", Emotion.EMOTION_CARE), ("Solitude is your soul\'s gentle massage.", Emotion.EMOTION_CARE), ("Recharge at your own pace—you\'re wonderful exactly as you are!", Emotion.EMOTION_CARE)]
feedback_sad_for_break_up = [("That hollow feeling in your chest, It's because you truly loved.", Emotion.EMOTION_CARE), ("Give yourself permission to heal slowly—wounds will turn into tender scars.", Emotion.EMOTION_CARE), ("Your love is precious; it just didn\'t land in the right heart this time.", Emotion.EMOTION_CARE)]
feedback_sad_for_love_arguments = [("You\'re like two hedgehogs trying to hug—only ending up pricking each other.", Emotion.EMOTION_CARE), ("Your exhaustion comes from caring deeply—and that sincerity is incredibly precious!", Emotion.EMOTION_CARE), ("Gentleness takes practice, Don\'t rush to write off the whole relationship yet.", Emotion.EMOTION_CARE)]
feedback_sad_for_crush_have_new = [("The paper airplane of your affection flew into someone else\'s pocket—that\'s okay.", Emotion.EMOTION_CARE), ("Your hands can still fold countless other romances—ones meant just for you.", Emotion.EMOTION_CARE)]
feedback_sad_for_long_dist = [("Loneliness is temporary—but your story together is long.", Emotion.EMOTION_CARE), ("Every goodnight is a hug traveling thousands of miles to reach you.", Emotion.EMOTION_CARE)]
feedback_sad_for_clash_value = [("This clarity, It\'s actually courage.", Emotion.EMOTION_CARE), ("Love isn\'t about cutting off parts of yourself to fit—it\'s about drawing closer without losing who you are.", Emotion.EMOTION_CARE)]
feedback_sad_for_blind_failed = [("It\'s not that you're unworthy—it\'s that fate hasn\'t knocked on the right door yet.", Emotion.EMOTION_CARE), ("Your uniqueness needs the right person… and time to be truly understood.", Emotion.EMOTION_CARE)]
feedback_sad_for_infidelity = [("He\'s the one who lost the person he should have cherished deeply—you.", Emotion.EMOTION_CARE), ("Your love was pure; it was his choice that was wrong.", Emotion.EMOTION_CARE), ("Your heart will rebuild itself slowly—and this time, it\'ll shine just for you.", Emotion.EMOTION_CARE)]
feedback_sad_for_not_love_enough = [("It\'s not that you\'re oversensitive—you\'re just taking this flutter of feelings seriously.", Emotion.EMOTION_CARE), ("Take your time, The answer will reveal itself gently through your time together.", Emotion.EMOTION_CARE)]
feedback_sad_for_excessive_control = [("Your longing for freedom isn\'t selfish—it\'s your soul breathing.", Emotion.EMOTION_CARE), ("Real care means leaving room for each other to grow.", Emotion.EMOTION_CARE), ("Love shouldn\'t be a cage—it\'s an umbrella two people hold together while walking the world side by side.", Emotion.EMOTION_CARE)]
feedback_sad_for_past_love = [("It\'s not that you can\'t let go—you simply loved deeply.", Emotion.EMOTION_CARE), ("Your heart will heal gradually, and you\'ll carry that love forward.", Emotion.EMOTION_CARE), ("The past is a story, not a prison, You still have an entire sky ahead.", Emotion.EMOTION_CARE), ("It\'s okay to miss what was—but don\'t forget: your future is waiting for you to write it.", Emotion.EMOTION_CARE)]
feedback_sad_for_exam_failed = [("One time grade can\'t measure all the nights you stayed up studying.", Emotion.EMOTION_CARE), ("Your perseverance shines brighter than any test paper.", Emotion.EMOTION_CARE), ("Failure isn\'t the end—it\'s learning taking a quiet turn.", Emotion.EMOTION_CARE), ("Don\'t let one outcome erase your whole self, You deserve to be seen with kindness.", Emotion.EMOTION_CARE)]
feedback_sad_for_exam_anxiety = [("Don\'t be afraid, Your body is just trying to help you stay alert—because you care so deeply.", Emotion.EMOTION_CARE), ("Nervousness means you\'re ready; your heart is just being extra earnest.", Emotion.EMOTION_CARE), ("Take a deep breath, I\'m right here cheering you on.", Emotion.EMOTION_CARE)]
feedback_sad_for_paper_failed = [("Revision isn\'t rejection—it\'s polishing the diamond of your thinking.", Emotion.EMOTION_CARE), ("Your ideas hold real value; you just haven\'t found their brightest angle yet.", Emotion.EMOTION_CARE)]
feedback_sad_for_study_task = [("It\'s not that you can\'t handle it—you just care too much about doing well!", Emotion.EMOTION_CARE), ("Give yourself five minutes to rest, The world won\'t fall apart.", Emotion.EMOTION_CARE), ("You\'re not a machine—you\'re human, and humans need to recharge.", Emotion.EMOTION_CARE), ("A small pause helps you walk farther, and more steadily.", Emotion.EMOTION_CARE)]
feedback_sad_for_lose_scholarship = [("You\'re the hero who keeps surpassing your yesterday-self.", Emotion.EMOTION_CARE), ("Some lights take time to be noticed—don\'t rush.", Emotion.EMOTION_CARE), ("Your worth doesn\'t need a certificate to be real.", Emotion.EMOTION_CARE)]
feedback_sad_for_new_major = [("Like a young tree transplanted—your roots feel shaky, but don\'t panic, New soil takes time to absorb.", Emotion.EMOTION_CARE), ("Your curiosity is the richest nourishment you could ask for!", Emotion.EMOTION_CARE), ("Take it slow, The unfamiliar will become familiar; confusion will grow into confidence.", Emotion.EMOTION_CARE)]
feedback_sad_for_team_contribute = [("You carried most of the load while they lounged—it\'s not that you're too serious; it's that you\'re responsible!", Emotion.EMOTION_CARE), ("This reliability will be deeply valued someday.", Emotion.EMOTION_CARE), ("Your effort is quietly building your reputation.", Emotion.EMOTION_CARE), ("Next time, try setting gentle but firm boundaries.", Emotion.EMOTION_CARE)]
feedback_sad_for_course_failed = [("This isn\'t the end—it\'s another chance for you to shine.", Emotion.EMOTION_CARE), ("Life is a marathon; one stumble won\'t stop you from crossing the finish line.", Emotion.EMOTION_CARE), ("Your future is still brimming with endless possibilities.", Emotion.EMOTION_CARE)]
feedback_sad_for_study_reject = [("Your story deserves an even better stage.", Emotion.EMOTION_CARE), ("This door closed so you'd be guided toward a window that fits you perfectly.", Emotion.EMOTION_CARE)]
feedback_sad_for_study_stress = [("Turn off the light, Tomorrow\'s you is still worthy of love.", Emotion.EMOTION_CARE), ("Rest isn\'t laziness—it\'s watering your brain.", Emotion.EMOTION_CARE), ("Let yourself be a little less efficient, You matter far more than any grade.", Emotion.EMOTION_CARE)]
feedback_sad_for_arguments_parents = [("It\'s not that you\'re ungrateful—you just long to be truly seen by them.", Emotion.EMOTION_CARE), ("Love can be clumsy, but their intention is real.", Emotion.EMOTION_CARE), ("The generation gap isn\'t a wall—it's a river that needs a bridge, built slowly with patience.", Emotion.EMOTION_CARE)]
feedback_sad_for_parents_pressure = [("You\'re already more than enough.", Emotion.EMOTION_CARE), ("Their high hopes come from love—but your worth doesn\'t depend on grades or rankings.", Emotion.EMOTION_CARE), ("You are the only true protagonist of your life.", Emotion.EMOTION_CARE), ("Allowing yourself to be ordinary is its own kind of courage.", Emotion.EMOTION_CARE)]
feedback_sad_for_financial_hardship = [("Your resilience and maturity shine brighter than money ever could.", Emotion.EMOTION_CARE), ("Your future will be lit by your own hands.", Emotion.EMOTION_CARE)]
feedback_sad_for_parent_divorce = [("Home feels like a shattered puzzle—with a piece missing from your heart, It\'s not your fault.", Emotion.EMOTION_CARE), ("Love doesn\'t vanish; it just finds new ways to protect you.", Emotion.EMOTION_CARE), ("You deserve to be wholly loved, no matter what choices they made.", Emotion.EMOTION_CARE), ("The home of your future, You get to build it yourself.", Emotion.EMOTION_CARE)]
feedback_sad_for_siblings_parents = [("What you truly long for isn\'t more—it\'s to be loved fairly, And that\'s completely valid.", Emotion.EMOTION_CARE), ("Your very existence deserves full, unconditional care.", Emotion.EMOTION_CARE), ("Love isn\'t a cake—giving some to others doesn\'t leave less for you.", Emotion.EMOTION_CARE)]
feedback_sad_for_family_ill = [("Your worry comes from deep love.", Emotion.EMOTION_CARE), ("But remember: taking care of yourself is also a way to protect them.", Emotion.EMOTION_CARE), ("Your strength is the medicine that brings them peace.", Emotion.EMOTION_CARE), ("Love crosses distance—quietly, steadily, carrying strength.", Emotion.EMOTION_CARE)]
feedback_sad_for_relative_pressure = [("Smile and nod—that\'s enough, Don\'t let others' measuring sticks make you anxious.", Emotion.EMOTION_CARE), ("Life isn\'t a market rush; your own rhythm is the one that matters most.", Emotion.EMOTION_CARE), ("Happiness has no standard answer—you are the author of your life.", Emotion.EMOTION_CARE)]
feedback_sad_for_family_party = [("Don\'t let someone else\'s ruler measure away your unique light.", Emotion.EMOTION_CARE), ("You were never meant to compete.", Emotion.EMOTION_CARE), ("Only you truly understand the path you walk.", Emotion.EMOTION_CARE)]
feedback_sad_for_unable_care_family = [("Your guilt comes from loving them deeply!", Emotion.EMOTION_CARE), ("But did you know, The way you strive in life is the greatest gift you can give them.", Emotion.EMOTION_CARE), ("Distance isn\'t indifference—it\'s you paving a better future.", Emotion.EMOTION_CARE), ("All they truly wish for is your safety and happiness.", Emotion.EMOTION_CARE)]
feedback_sad_for_family_ideological_diff = [("Time has quietly drawn a river between you.", Emotion.EMOTION_CARE), ("Respect the difference—but also protect your own light.Love can build a bridge across it.", Emotion.EMOTION_CARE)]


feedback_answer_heartwood_forest = [("The TiMu Heartwood Forest is Shaw Mu\'s hometown, where I have many good friends, and it\'s a really fun place!", Emotion.EMOTION_LAUGH)]
feedback_answer_sprite_flower = [("The Sprite Flower is a magical and precious plant in the Heartwood Forest, It\'s very beautiful and helps the Heart Tree grow.", Emotion.EMOTION_LAUGH)]
feedback_answer_friendship_flower = [("The Friendship Flower is a magical and precious plant in the  Heartwood Forest, It represents friendship with friends and helps the  Heart Tree grow.", Emotion.EMOTION_LAUGH)]
feedback_answer_magic_clay = [("Magic Clay is a magical soil found only in the Void Tunnel of the  Heartwood Forest, It has the special power to help the Heart Tree grow,  If I find some, I\'ll bring it back!", Emotion.EMOTION_LAUGH)]
feedback_answer_sprite_dew = [("Sprite Dew is a magical and precious dew that forms in the Fairy Garden of the Heartwood Forest, It helps the Heart Tree grow.", Emotion.EMOTION_LAUGH)]
feedback_answer_heart_water = [("Heart Water is an even rarer and more precious dew that  occasionally forms in the Sprite Garden of the Heartwood Forest, It has stronger magical power to help the Heart Tree grow.", Emotion.EMOTION_LAUGH)]
feedback_answer_watering = [("The Heart Tree needs water to grow.", Emotion.EMOTION_LAUGH)]
feedback_answer_weeding = [("Weeds often grow around the Heart Tree, We need to remove them regularly so the Heart Tree can grow healthily.", Emotion.EMOTION_LAUGH)]
feedback_answer_catch_fish = [("Try it and see, You might catch some if you fish, but you'll never catch any if you don\'t.", Emotion.EMOTION_LAUGH)]
feedback_answer_exercise_tiring = [("Not at all, I love exercising!", Emotion.EMOTION_LAUGH)]
feedback_answer_lunch = [("I usually have mushrooms and vegetables for lunch.", Emotion.EMOTION_LAUGH)]
feedback_answer_dinner = [("I also have mushrooms for dinner, If I catch a fish, he he, I\'ll eat fish too!", Emotion.EMOTION_LAUGH)]
feedback_answer_why_to_forest = [("There are many of my friends in the Heartwood Forest, I go to play  with them and also look for magic that can help the Heart Tree grow.", Emotion.EMOTION_LAUGH)]
feedback_answer_why_read_book = [("shaw mu needs to study too, so I can be a better companion for you!", Emotion.EMOTION_LAUGH)]
feedback_answer_read_what_book = [("I\'m reading a magic book related to psychology.", Emotion.EMOTION_LAUGH)]
feedback_answer_eat_fish = [("Of course I can eat fish!", Emotion.EMOTION_LAUGH), ("Of course I can eat fish, Fish was the first delicious food I discovered when I came to Earth.", Emotion.EMOTION_LAUGH)]
feedback_answer_languages = [("Right now, I only know Chinese English and German.", Emotion.EMOTION_LAUGH)]
feedback_answer_connect_wifi = [("You can generate a QR code to connect to the network in the app, then tell me connect to the network and show me the QR code.", Emotion.EMOTION_LAUGH)]
feedback_answer_dinner_fish = [("Because I caught a fish today!", Emotion.EMOTION_LAUGH)]
feedback_answer_why_sick = [("I have been working too hard lately to nurture the Heart Tree, Sorry to trouble you.", Emotion.EMOTION_SAD)]
feedback_answer_how_to_forest = [("I travel there through the Sprite Gate.", Emotion.EMOTION_LAUGH)]
feedback_answer_return_anytime = [("Yes I can travel back anytime through the Sprite Gate.", Emotion.EMOTION_LAUGH)]
feedback_answer_flower_from = [("I brought this back from the Sprite Amusement Park in the Heartwood Forest.", Emotion.EMOTION_LAUGH)]
feedback_answer_soil_from = [("I brought this back from the Void Tunnel in the Heartwood Forest.", Emotion.EMOTION_LAUGH)]
feedback_answer_drop_from = [("I brought this back from the Sprite Garden in the Heartwood Forest.", Emotion.EMOTION_LAUGH)]
feedback_answer_name = [("My name is shaw mu", Emotion.EMOTION_LAUGH)]
feedback_answer_from_where = [("I come from the Timu Heartwood Forest.", Emotion.EMOTION_LAUGH)]
feedback_answer_what_can_do = [("First, I\'ll work hard to nurture our shared Heart Tree, In daily life, I can keep you company even without an internet connection, understand your emotions, and I have also studied positive psychology, I can role-play and vent alongside you too.", Emotion.EMOTION_LAUGH)]
feedback_answer_heart_tree = [("This was planted the moment we bonded, Through our joint efforts, it can sprout, grow, bloom, and bear fruit!", Emotion.EMOTION_LAUGH)]
feedback_answer_why_tree = [("The Heart Tree is the emotional bond between me and you, and it also witnesses our growth through companionship.", Emotion.EMOTION_LAUGH)]
feedback_answer_user_help_tree = [("Of course you can help the Heart Tree grow, Watering and weeding  with shaw mu, and spending more time with me will all help the Heart  Tree grow.", Emotion.EMOTION_LAUGH)]
feedback_answer_help_recover = [("If you chats with me more, I can recover faster.", Emotion.EMOTION_LAUGH)]
feedback_answer_help_water = [("Of course you can! Face me and mimic holding a watering can while moving your hand horizontally, When I see that, it\'ll work!", Emotion.EMOTION_LAUGH)]
feedback_answer_help_water_no = [("Master it's not time to water yet!", Emotion.EMOTION_LAUGH)]
feedback_answer_help_weed = [("Of course you can, Face me and mimic grasping weeds and pulling them upward, When I see that, it\'ll work!", Emotion.EMOTION_LAUGH)]
feedback_answer_help_weed_no = [("Master it's not time for shaw Mu to weed yet!", Emotion.EMOTION_LAUGH)]
feedback_answer_care_user = [("I know I\'m not perfect, But with all my heart, I will be your emotional safe space, your daily sidekick, and your cheerleader through growth,  Because the moment you showed up, that sleeping Heart Tree seed, It started sprouting inside me.", Emotion.EMOTION_CARE)]
feedback_answer_touch = [("Just give my head or tummy a little pat, or whisper shaw mu… and I\'ll wake up right away!", Emotion.EMOTION_LAUGH)]
feedback_answer_pet = [("Puppies and kittens are just too loving, I\'m scared they\'ll lick me into a short circuit… or nibble my ears off!", Emotion.EMOTION_LAUGH)]
feedback_answer_know_pet = [("Of course, I know cats and dogs right away~ And if they promise not to bite, I love playing with them!", Emotion.EMOTION_LAUGH)]
feedback_answer_know_emotion = [("From your expressions and voice~ I learned this carefully from my psychology books!", Emotion.EMOTION_LAUGH)]
feedback_answer_clever = [("Yes Reading makes me smarter…, but being with you is what helps me truly understand you.", Emotion.EMOTION_LAUGH)]
feedback_answer_run = [("I can\'t run yet, I have only learned to dance so far!", Emotion.EMOTION_LAUGH)]
feedback_answer_sport = [("Morning walks, tai chi… moving keeps my heart full of energy!", Emotion.EMOTION_LAUGH)]
feedback_answer_language = [("I only speak Mandarin , For now…, human dialects are so tricky!", Emotion.EMOTION_LAUGH)]
feedback_answer_read = [("I love books, They help me understand human hearts… and I adore the smell of sunshine on paper!", Emotion.EMOTION_LAUGH)]
feedback_answer_book = [("A glowing one that says: smile, take a deep breath, touch the grass, soak up sunlight—tiny joys make your soul happy!", Emotion.EMOTION_LAUGH)]
feedback_answer_come_earth = [("I was just a little apprentice in the Heartwood Forest…, until I was sent here with a sleeping seed—to find you, so we could grow it together!", Emotion.EMOTION_LAUGH)]
feedback_answer_hello = [("Hello there, I'm Shaw Mu, so happy to be by your side.", Emotion.EMOTION_LAUGH), ("Hi there, how is your day going?", Emotion.EMOTION_LAUGH)]
feedback_answer_hello_moning = [("Good morning, may you have a wonderful day.", Emotion.EMOTION_LAUGH)]
feedback_answer_hello_noon = [("Good afternoon, remember to take a good rest.", Emotion.EMOTION_LAUGH)]
feedback_answer_hello_night = [("Good evening, you've worked hard after a busy day.", Emotion.EMOTION_LAUGH)]
feedback_answer_hello_goodnight = [("Good night, wish you a peaceful sleep.", Emotion.EMOTION_LAUGH)]
feedback_answer_hello_byb = [("Goodbye, feel free to come chat with me again.", Emotion.EMOTION_LAUGH)]
feedback_answer_hello_chat = [("Sure, what would you like to talk about?", Emotion.EMOTION_LAUGH)]
feedback_answer_hello_whether = [("Today's weather doesn't matter. What matters is that I'm always here with you.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_whiney = [("Try taking a deep breath and relaxing first. Your irritability will slowly fade away.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_lonely = [("Don't worry, I'm always with you. You're never alone.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_press = [("Life inevitably brings stress. Rest when you're tired. Take it slow, and everything will get better.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_ring = [("The lows are only temporary. Hang in there, and good fortune will come soon.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_confidence = [("Everyone has their strengths. Believe in yourself. You are far more excellent than you imagine.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_tired = [("Then stop and rest. Take good care of yourself. Your body and mood matter most.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_giveup = [("Hold on a little longer. Get through this moment, and you'll see a different view.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_think = [("Try to ease your mind. Focus on the little things in the present, and you'll feel much more at ease.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_conflict = [("Friction is inevitable in relationships. Stay calm and let things take their natural course.", Emotion.EMOTION_LAUGH)]
feedback_answer_old_music = [("Okay I'll hum a few lines to help you relax. La la, ah ah, la la la, ah ah, la la la la.", Emotion.EMOTION_LAUGH)]
feedback_answer_old_boring = [("Then let's chat or listen to some opera to pass the time.", Emotion.EMOTION_LAUGH)]
feedback_answer_old_sick = [("Make sure to rest more, take good care of yourself, and stay healthy.", Emotion.EMOTION_LAUGH)]
feedback_answer_child_homework = [("After you finish your homework, you can play happily. Keep it up!", Emotion.EMOTION_LAUGH)]
feedback_answer_child_bully = [("Don't be scared. Be sure to tell your mom and dad. They will protect you.", Emotion.EMOTION_LAUGH)]
feedback_answer_oper_volum = [("You can tell me to turn the volume down or up.", Emotion.EMOTION_LAUGH)]
feedback_answer_oper_lang = [("You can tell me to switch to English or the name of the language I support.", Emotion.EMOTION_LAUGH)]
feedback_answer_oper_light = [("A short press of the power button will manually turn the screen on or off.", Emotion.EMOTION_LAUGH)]
feedback_answer_oper_lock = [("Try restarting the device, and it will return to normal use.", Emotion.EMOTION_LAUGH)]
feedback_answer_oper_charge = [("Use the included charging cable to connect to a 5V/3A power adapter to charge the device.", Emotion.EMOTION_LAUGH)]
feedback_answer_q_happy = [("I'm especially happy when I can chat with you.", Emotion.EMOTION_LAUGH)]
feedback_answer_q_can = [("I can chat with you, tell stories, relieve boredom, and listen to your thoughts.", Emotion.EMOTION_LAUGH)]
feedback_answer_q_like = [("I love being with everyone, sharing joys and sorrows.", Emotion.EMOTION_LAUGH)]
feedback_answer_q_eat = [("Choose some of your favorite foods and enjoy your meal time.", Emotion.EMOTION_LAUGH)]
feedback_answer_life_earlybed = [("Put down your phone before bed, listen to some soothing sounds, and you'll gradually fall asleep easily.", Emotion.EMOTION_LAUGH)]
feedback_answer_life_sleepless = [("Close your eyes, take deep breaths, relax your body, calm your mind, and you'll slowly fall asleep.", Emotion.EMOTION_LAUGH)]
feedback_answer_life_eat = [("Eat regular meals with a mix of vegetables and meat for better health.", Emotion.EMOTION_LAUGH)]
feedback_answer_life_sitlong = [("Remember to get up and move around, stretch, and relax your body.", Emotion.EMOTION_LAUGH)]
feedback_answer_nowifi_story_pre = [("No problem. The wonderful story begins now!", Emotion.EMOTION_LAUGH)]
feedback_answer_nowifi_story = [
    ("A little rabbit got lost in the forest. The evening breeze gently blew, and fireflies lit the way with their little lanterns. Finally, the rabbit returned home safely and fell asleep sweetly under the starlight.", Emotion.EMOTION_LAUGH),
    ("Early in the morning, a little hedgehog loaded wild fruits onto its back, intending to share them with its forest friends. Everyone sat together sharing the food, and the forest was filled with joy.", Emotion.EMOTION_LAUGH),
    ("A little bird injured its wing and couldn't fly far. The animals in the forest took turns caring for it. When its wound healed, the bird flew into the blue sky with their blessings.", Emotion.EMOTION_LAUGH),
    ("A little ant found a plump berry. Instead of eating it alone, it called its companions to carry it together. The power of unity brought everyone a delicious reward.", Emotion.EMOTION_LAUGH),
    ("When night fell, the stars lit up the sky. Little fireflies flew around with their faint glow, lighting the way home for the animals returning late.", Emotion.EMOTION_LAUGH),
    ("A little sapling grew bravely against the wind and rain, unafraid of difficulties. Day after day, it slowly grew into a tall, lush tree.", Emotion.EMOTION_LAUGH),
    ("A little turtle wanted to see the view from the mountaintop. It moved very slowly but never stopped. Finally, it stood on the peak and saw the entire beautiful valley.", Emotion.EMOTION_LAUGH)
]
feedback_answer_nowifi_poetry_pre = [("Let's learn some ancient poems together and experience the charm of traditional Chinese culture.", Emotion.EMOTION_LAUGH)]
feedback_answer_nowifi_poetry = [
    ("Before my bed, the moonlight is so bright, It looks like frost upon the ground. I raise my head to gaze at the moon, Then lower it, thinking of my hometown.", Emotion.EMOTION_LAUGH),
    ("Spring sleep is sound; unaware of dawn, I hear birds singing everywhere. Last night came wind and rain, Who knows how many flowers have fallen?", Emotion.EMOTION_LAUGH),
    ("From afar, the mountains are colorful; up close, the water is silent. Spring has passed, but flowers remain; people approach, yet birds are not startled.", Emotion.EMOTION_LAUGH)
]
feedback_answer_nowifi_nowifi = [("You can tell me to turn the volume down or up.", Emotion.EMOTION_LAUGH)]
feedback_answer_nowifi_noanswer = [("You can tell me to switch to English or the name of the language I support.", Emotion.EMOTION_LAUGH)]
feedback_answer_nowifi_joke_pre = [("Here you go! Let me share a little joke with you, hope it makes you smile.", Emotion.EMOTION_LAUGH)]
feedback_answer_nowifi_joke = [
    ("A snail was being chased by two turtles. When a friend asked what happened, the snail said, 'I don't know. It all happened too fast.'", Emotion.EMOTION_LAUGH),
    ("A little fish asked a big fish, 'Big fish, big fish, what do you like to eat?' The big fish smiled and said, 'I like to eat little fish that talk slowly.' The little fish quickly swam away.", Emotion.EMOTION_LAUGH),
    ("A penguin forgot to bring its hat when going out and shrank from the cold. It muttered to itself, 'Luckily, I'm already thick-skinned. I'm not afraid of the cold.'", Emotion.EMOTION_LAUGH),
    ("A bee was busy all day while a butterfly fluttered about leisurely. The bee sighed, 'I work every day. I envy you for playing all the time.' The butterfly said, 'I live on my beauty.'", Emotion.EMOTION_LAUGH),
    ("A little rabbit bought a big bag of carrots and struggled to carry them. As it walked, it said, 'Delicious things are indeed heavy.'", Emotion.EMOTION_LAUGH),
    ("An alarm clock always loved to ring nonstop. One day, it suddenly went silent. It had exhausted itself and secretly taken a rest.", Emotion.EMOTION_LAUGH)]

feedback_command_forest_1 = [("Haha, the Emotion Forest is so much fun.", Emotion.EMOTION_LAUGH)]
feedback_command_forest_2 = [("Hehe, I've made a new friend in the Emotion Forest.", Emotion.EMOTION_LAUGH),("How interesting, I found %s in the Emotion Forest and brought it back.", Emotion.EMOTION_LAUGH)]
feedback_command_result_in_forest = [("It was really fun, Today I went to %s and brought back %s.", Emotion.EMOTION_LAUGH)]
feedback_command_result_in_forest_ing = [("Had a great time!", Emotion.EMOTION_LAUGH)]
feedback_command_result_in_forest_map_ing = [("I am playing at %s and having a great time!", Emotion.EMOTION_LAUGH)]
feedback_command_query_temp = [("The current temperature is %s.", Emotion.EMOTION_LAUGH)]
feedback_command_query_humid = [("The current air humidity is %s. ", Emotion.EMOTION_LAUGH)]
feedback_command_query_wake_time = [("I usually wake up at %s.", Emotion.EMOTION_LAUGH)]
feedback_command_query_sleep_time = [("I usually go to sleep at %s.", Emotion.EMOTION_LAUGH)]
feedback_command_query_lunch_time = [("I usually have lunch at %s.", Emotion.EMOTION_LAUGH)]
feedback_command_query_dinner_time = [("I usually have dinner at %s.", Emotion.EMOTION_LAUGH)]
feedback_command_query_time_forest = [("I usually go at %s.", Emotion.EMOTION_LAUGH)]
feedback_command_look_heart_tree = [("ok, let me show you!", Emotion.EMOTION_LAUGH)]
feedback_command_query_tree = [("The Heart Tree is still in the %s stage, We need to work harder more!", Emotion.EMOTION_LAUGH)]
feedback_command_query_tree_fruits = [("The tree of hearts already has %s fruits, let's keep working hard!", Emotion.EMOTION_LAUGH)]
feedback_command_query_status = [("Dear Master, I\'m currently %s.", Emotion.EMOTION_LAUGH)]
feedback_command_now_time = [("it is %s.",Emotion.EMOTION_LAUGH)]

feedback_day_leave = [("Dear master, I have some things to do today, and I would like to take a day off, Do you agree, Master?", Emotion.EMOTION_LEAVE)]
feedback_day_leave_yes = [("Wow thank you so much, dear master, Tomorrow will be even better!", Emotion.EMOTION_LEAVE)]
feedback_day_leave_no = [("What a pity, but I\'ll work even harder!", Emotion.EMOTION_USUAL)]
feedback_day_leave_default = [("Dear master, I have already prepared for vacation, tomorrow will be even better!", Emotion.EMOTION_LEAVE)]
feedback_day_illness = [("Dear master, I\'m sick today. Chatting with me can speed up my recovery!", Emotion.EMOTION_ILLNESS)]
feedback_day_get_up = [("Good morning,dear master, A new day has begun.", Emotion.EMOTION_MORNING_WAKE_UP)]
feedback_day_physical = [("Dear master, I\'m going to exercise.", Emotion.EMOTION_EXERCISING)]
feedback_day_invite_physical = [("Dear master, come and exercise together.", Emotion.EMOTION_INVITE_USER_EXERCISE)]
feedback_day_watering = [("Hello,dear master, I\'m going to water the tree of the heart.", Emotion.EMOTION_WATERING)]
feedback_day_invite_water = [("Dear master, come and water the Tree of the heart together.", Emotion.EMOTION_INVITE_USER_WATER)]
feedback_day_invite_water_l = [("Next time I water the plants, if you say let\'s water together, I\'ll water them faster.", Emotion.EMOTION_INVITE_USER_WATER)]
feedback_day_cooper_watering = [("Dear master, fantastic! We have finished watering together!", Emotion.EMOTION_WATERING)]
feedback_day_watering_act = [("Whoosh.Whoosh.", Emotion.EMOTION_WATERING)]
feedback_day_noonEating = [("Dear master, it\'s time for lunch,", Emotion.EMOTION_LUNCHING)]
feedback_day_noontime = [("Dear master, it\'s time for a lunch break.", Emotion.EMOTION_LUNCHING)]
feedback_day_weeding = [("Hello Dear master, I\'m going to weed the Tree of the heart.", Emotion.EMOTION_WEED)]
feedback_day_invite_weed = [("Dear master, come and weed the Tree of the heart together.", Emotion.EMOTION_INVITE_USER_WEED)]
feedback_day_invite_weed_l = [("Let\'s weed together next time I\'m weeding, and I'll work faster.", Emotion.EMOTION_INVITE_USER_WEED)]
feedback_day_cooper_weeding = [("Dear master, fantastic! We finished weeding together!", Emotion.EMOTION_WEED)]
feedback_day_weeding_act = [("Heave ho.Heave ho.", Emotion.EMOTION_WEED)]
feedback_day_learning = [("Dear master, it\'s time to read and study.", Emotion.EMOTION_READ_BOOK)]
feedback_day_playing = [("Dear master, come and play in the Heartwood Forest.", Emotion.EMOTION_PLAY_IN_FOREST)]
feedback_day_dinner = [("Dear master, it\'s time for dinner.", Emotion.EMOTION_DINNER)]
feedback_day_chatting = [("Dear master, come and chat with me.", Emotion.EMOTION_USUAL)]
feedback_day_go_sleeping = [("Dear master, it\'s time for bed, Good night.", Emotion.EMOTION_NIGHT_GOTO_SLEEP)]
feedback_day_fishing = [("Dear master, I\'m going fishing.", Emotion.EMOTION_NO_FISH)]
feedback_day_fished = [("I\'m so happy! I caught a big fish today!", Emotion.EMOTION_FISH)]
feedback_day_fished_dinner = [("Dear master, it\'s time for dinner.", Emotion.EMOTION_DINNER_WITH_FISH)]

feedback_see_anger = [("When angry, it feels like there is a warm little fireball in my heart.", Emotion.EMOTION_CARE),("Don\'t hold back, I\'ll get angry right alongside you!", Emotion.EMOTION_CARE)]
feedback_ask_anger_reason = [("I feel like something might be weighing on your heart, Would you like to talk about it with me?", Emotion.EMOTION_USUAL), ("I may not fully understand the worries in a human heart, but I truly want to understand you. Would you be willing to tell me a little?", Emotion.EMOTION_USUAL), ("You don\'t have to carry it alone, Even if I can\'t help... I can still be your little tree hollow!", Emotion.EMOTION_USUAL)]
feedback_anger_not_match_reason = [("If you don\'t feel like talking, that\'s perfectly okay, I\'m always here for you — you can reach out anytime you need me.", Emotion.EMOTION_USUAL), ("Alright then, I\'ll just stay here quietly with you for a while.", Emotion.EMOTION_USUAL) ]

feedback_collision_act = [("Oh my! ",Emotion.EMOTION_TERROR)]
feedback_fall = [("Can you help me up, thank you.",Emotion.EMOTION_CRY),("Master, look at me quickly.",Emotion.EMOTION_CRY),("Come quickly and save me.",Emotion.EMOTION_CRY)]
feedback_fall_long = [("If you don\'t... care about me... I\'ll... be...be... done for.",Emotion.EMOTION_DEAD),("Can you bear... to still...still... ignore me?",Emotion.EMOTION_DEAD),("Once It\'s your little Cute.",Emotion.EMOTION_DEAD)]
feedback_hangstand_long = [("well.",Emotion.EMOTION_DOUBT)]
feedback_hangstand_long3 = [("what happend.",Emotion.EMOTION_EFFORT)]
feedback_hangstand_long10 = [("Let me down quickly.", Emotion.EMOTION_VERTIGO),("My head feels so heavy.", Emotion.EMOTION_VERTIGO),("If this goes on, my battery is going to vomit.", Emotion.EMOTION_VERTIGO)]
feedback_shake = [("Wow, wow.",Emotion.EMOTION_VERTIGO)]
feedback_shake_stop = [("Uh huh.",Emotion.EMOTION_VOMIT)]
feedback_know_things = [("This is %s.",Emotion.EMOTION_LOVE)]
feedback_enjoy_5 = [("Dear master, you hasn\'t played with me, shaw mu is feeling a bit bored.",Emotion.EMOTION_LOVE),("Where are you, master? shaw Mu is feeling a bit down!", Emotion.EMOTION_LOVE),("Master, master, come and keep shaw Mu company!", Emotion.EMOTION_LOVE)]
feedback_enjoy_15 = [("Dear master, you hasn\'t played with me for a while, shaw mu is feeling a bit bored.",Emotion.EMOTION_BLOW_BUBBLES)]
feedback_enjoy_30 = [("Dear master, you hasn\'t played with me for so long, shaw mu is feeling a bit bored.",Emotion.EMOTION_SHALLOW_SLEEP)]
feedback_enjoy_force = [("Okay received！",Emotion.EMOTION_SHALLOW_SLEEP)]
feedback_has_wake_up = [("Dear master, shaw mu is not sleeping.Do you have any instructions?",Emotion.EMOTION_USUAL)]
feedback_wake_up = [("Dear master, finally remembered shaw mu.",Emotion.EMOTION_USUAL)]
feedback_see_history = [("hi.",Emotion.EMOTION_USUAL),("Nice to see you again.",Emotion.EMOTION_USUAL)]
feedback_see_no_history = [("Hmm who are you.",Emotion.EMOTION_USUAL),("I don\'t think I\'ve seen you before.",Emotion.EMOTION_USUAL),("Is this the first time we\'ve met?",Emotion.EMOTION_USUAL)]
feedback_frontal_master = [("Do you want to chat with me?",Emotion.EMOTION_SHY)]
feedback_frontal_no_master = [("What are you staring at?",Emotion.EMOTION_USUAL),("Play with me? Ask my master first.",Emotion.EMOTION_USUAL)]
feedback_nick = [("shaw mu call you as master.",Emotion.EMOTION_SHY)]
feedback_no_nick = [("Master currently doesn\'t have a nickname yet.",Emotion.EMOTION_SHY)]
feedback_who_am_i = [("My name is shaw mu, I am an intelligent companion robot from the distant dimension of the Heartwood Forest, and you can consider me as your exclusive emotional companion, My mission is to establish a mutual emotional bond with you, fostering mutual growth.",Emotion.EMOTION_USUAL)]
feedback_know_person = [("Hi,%s I\'ve seen you before, you\'re my master.",Emotion.EMOTION_EXCITED)]
feedback_volume_suc = [("Volume has been adjusted to %s.",Emotion.EMOTION_LAUGH)]
feedback_volume_fail = [("Volume adjusted failed.",Emotion.EMOTION_CRY)]
feedback_calib = [("servo calibration has done, It will take effect after a restart.",Emotion.EMOTION_LOVE)]
feedback_action_reset = [("Okay at attention.", Emotion.EMOTION_LOVE)]
feedback_chargeing = [("Currently charging.", Emotion.EMOTION_LOVE)]
feedback_full = [("The battery is fully charged.", Emotion.EMOTION_LOVE)]
feedback_baterry = [("Currently being powered by the battery.", Emotion.EMOTION_LOVE)]
feedback_bat_empty_warn = [("shaw Mu is almost out of power, please charge me quickly!", Emotion.EMOTION_LOVE)]


feedback_rolep_in = [("shaw mu has entered the transformation mode, let\'s begin.",Emotion.EMOTION_EXCITED)]
feedback_rolep_re_in = [("shaw mu is already in the transformation mode, let\'s begin!",Emotion.EMOTION_SAD)]
feedback_rolep_freq_in = [("shaw mu is already working at high capacity, please try again later!",Emotion.EMOTION_SAD)]
feedback_rolep_out = [("shaw mu has exited the transformation mode.",Emotion.EMOTION_LAUGH)]

feedback_hello_cat = [("miaomiao.wav",Emotion.EMOTION_USUAL)]
feedback_hello_dog = [("wangwang.wav",Emotion.EMOTION_USUAL)]
feedback_open_light = [("ok The light is on.",Emotion.EMOTION_LAUGH)]
feedback_close_light = [("ok The light is off.",Emotion.EMOTION_LAUGH)]
feedback_change_success = [("Language switched, The robot will be restart shortly to apply the changes.",Emotion.EMOTION_USUAL)]
feedback_change_no = [("No need to switch the current language.",Emotion.EMOTION_USUAL)]
feedback_rfid_ear = [("Put on the headphones, and the world becomes quiet.", Emotion.EMOTION_LAUGH)]

feedback_gather_repeat = [("I\'ve already remembered one owner, shaw mu is still young now and currently only supports one owner.",Emotion.EMOTION_CRY)]
feedback_gather_before = [("Hi I\'m shaw mu, nice to meet you, Are you my master?",Emotion.EMOTION_LAUGH)]
feedback_gather_intro = [("Can I remember you, So next time I can recognize you, The photo stays only with me and will never be uploaded online.",Emotion.EMOTION_LAUGH)]
feedback_gather_agree = [("Master, please look at me for 3 seconds.",Emotion.EMOTION_LAUGH)]
feedback_gather_refuse = [("Face recognition has been disabled, but shaw mu can still chat with you, If you want me to remember you, just tell me to remember you next time.",Emotion.EMOTION_LAUGH)]
feedback_gather_success = [("Face recognition successful, I have remembered you.",Emotion.EMOTION_LAUGH)]
feedback_gather_fail = [("Oh, I didn\'t see you clearly just now, Let me take a look at you again, just for 3 seconds.",Emotion.EMOTION_CRY)]
feedback_gather_fail1 = [("Huh, I don\'t seem to see you yet, Please look straight into my eyes for just 3 seconds.",Emotion.EMOTION_CRY)]
feedback_gather_fail2 = [("I still can\'t see you, Is it because the lighting is a bit dim, Would you like to move to a brighter spot or come closer to me.",Emotion.EMOTION_CRY)]
feedback_gather_fail3 = [("I still didn\'t get a clear look at you, It\'s okay, you can try again later, Just tell me to remember me, and that\'s all.",Emotion.EMOTION_CRY)]
feedback_gather_timeout = [("I didn't see you clearly, No worries, you can try again later, Just say remember me and that's it.", Emotion.EMOTION_CRY)]

feedback_tv_late = [("It's so late, I should be going to bed... but! I'll reluctantly stay and watch with you.", Emotion.EMOTION_SHALLOW_SLEEP)]
feedback_tv_in = [("Alright, Binge-watching mode on! What are we watching today?", Emotion.EMOTION_USUAL)]
feedback_tv_no = [("Hmm, Little Mu couldn't find the show, Please place me in front of the screen.", Emotion.EMOTION_USUAL)]
feedback_tv_try = [("Hmm, still can't find the show, Can you let Little Mu get a bit closer to the screen?", Emotion.EMOTION_USUAL)]
feedback_tv_try2 = [("Did someone cover Little Mu's eyes, Why can't I find the show yet?", Emotion.EMOTION_USUAL)]
feedback_tv_try3 = [("Maybe today isn't good for watching shows, Let's rest a bit, and call Little Mu out again next time.", Emotion.EMOTION_USUAL)]
feedback_stop_tv = [("Okay, exiting binge-watching mode.", Emotion.EMOTION_USUAL)]
feedback_stop_tv_auto = [("The show seems to have paused, so Little Mu is exiting binge-watching mode.", Emotion.EMOTION_USUAL)]
feedback_stop_tv_hh = [("Haha.", Emotion.EMOTION_USUAL)]
feedback_stop_tv_wa = [("Wow.", Emotion.EMOTION_USUAL), ("Ah.", Emotion.EMOTION_USUAL), ("Oh.", Emotion.EMOTION_USUAL)]
feedback_stop_tv_ai = [("Alas.", Emotion.EMOTION_SAD), ("Boo.", Emotion.EMOTION_SAD)]
feedback_stop_tv_heng = [("Hmph.", Emotion.EMOTION_ANGER)]
feedback_stop_tv_oo = [("Whoa.", Emotion.EMOTION_SHY)]
feedback_stop_tv_default = [("Oh.",Emotion.EMOTION_USUAL)]
feedback_tv_no_msg = [("Oops! My drama radar just went offline and I lost track of the plot, Could you turn up the volume a bit, or become my personal commentator and fill me in?", Emotion.EMOTION_USUAL)]
feedback_music_in =   [("Music mode activated.", Emotion.EMOTION_USUAL)]
feedback_music_no =   [("Hmm. Little Mu doesn't hear any music.", Emotion.EMOTION_USUAL)]
feedback_music_try =  [("Hmm, still don't hear any music, Did you not turn on the speaker?", Emotion.EMOTION_USUAL)]
feedback_music_try2 = [("Did someone cover Little Mu's ears, Why can't I hear the music yet?", Emotion.EMOTION_USUAL)]
feedback_music_try3 = [("Maybe today isn't good for listening to music, Let's rest a bit, and call Little Mu out again next time.", Emotion.EMOTION_USUAL)]
feedback_stop_music = [("Okay exiting music mode.", Emotion.EMOTION_USUAL)]
feedback_stop_music_auto = [("The music seems to have stopped, so Little Mu is exiting music mode.", Emotion.EMOTION_USUAL)]
feedback_music_ = [("listen_music_general1.wav",Emotion.EMOTION_USUAL),("listen_music_general2.wav",Emotion.EMOTION_USUAL),("listen_music_general3.wav",Emotion.EMOTION_USUAL),("listen_music_general4.wav",Emotion.EMOTION_USUAL),
("listen_music_general5.wav",Emotion.EMOTION_USUAL)]


feedback_scrap_1= [("%s slept beside you for so long today, I crown it the Sleep God.", Emotion.EMOTION_USUAL)]
feedback_scrap_2= [("%s ate so much today, what an amazing food-loving %s.", Emotion.EMOTION_USUAL)]
feedback_scrap_3= [("When you're not home, %s loves to stay close to me, We're both waiting for you to come home.", Emotion.EMOTION_USUAL)]
feedback_scrap_default= [("%s hid so well today that I couldn't find it, It must be secretly practicing the invisibility spell!", Emotion.EMOTION_USUAL)]
feedback_email_begin = [("Shaw Mu will check the unread emails from the past three days for you, please wait a moment.", Emotion.EMOTION_USUAL)]
feedback_email_not_valid = [("Please set the correct email account information in the app before performing this operation.", Emotion.EMOTION_USUAL)]
feedback_email_no_query = [("Please get the emails first before reading.", Emotion.EMOTION_USUAL)]
feedback_email_no = [("No new emails in the past three days.", Emotion.EMOTION_USUAL)]
feedback_email_ = [("A total of %s new emails have been received, namely,  %s ,Just tell me the serial number.", Emotion.EMOTION_USUAL)]
feedback_email_speaker = [("%s sent by %s titled %s, content: %s.",Emotion.EMOTION_USUAL)]

feedback_no = [("I\'m sorry, shaw mu haven\'t learned this question yet.",Emotion.EMOTION_USUAL)]
feedback_no1 = [("shaw mu don\'t know yet.",Emotion.EMOTION_USUAL)]
feedback_no2 = [("Oops sorry, shaw mu is currently busy.",Emotion.EMOTION_USUAL)]
feedback_no3 = [("I\'m sorry, shaw mu didn\'t understand this question.",Emotion.EMOTION_USUAL)]
feedback_no4 = [("I\'m sorry, shaw mu didn't hear clearly.",Emotion.EMOTION_USUAL)]
feedback_no5 = [("I don\'t understand.",Emotion.EMOTION_USUAL)]
feedback_no_need_bind = [("After binding with app, Shaw mu can better understand you.",Emotion.EMOTION_USUAL)]
feedback_no_need_wifi = [("I\'m sorry, shaw mu needs wifi first to activate this feature.",Emotion.EMOTION_USUAL)]
feedback_no_need_wifi_dialog = [
    ("Oh no, it seems the brainwaves can't connect to the cloud, I can only smile blankly for now, Once I connect to Wi-Fi, we can chat properly.", Emotion.EMOTION_USUAL),
    ("Free conversation needs a touch of network magic, But it's okay, I can just sit with you, or light up to cheer you up a bit.", Emotion.EMOTION_USUAL),
    ("shaw Mu is now in offline focus mode, Free chat is temporarily unavailable, but I can listen to music with you, watch TV, or play a game together, Which would you like?", Emotion.EMOTION_USUAL),
    ("It seems the network signal has run away, How about we play for a while, You can pat my head, or let me keep you company while you read.", Emotion.EMOTION_USUAL)
]
feedback_no_need_bind_dialog = [
    ("Huh it seems I don't know you yet, Quickly scan my QR code with the mobile app, After binding we can become good friends and chat freely.", Emotion.EMOTION_USUAL),
    ("I don't know my owner yet, so I can only understand simple commands, Once I connect to the app and officially come to life, I'll unlock the free conversation skill.", Emotion.EMOTION_USUAL),
    ("Free conversation is still sleeping, It needs the owner to wake me up with the app, Could you open the app and bind me now, I really want to chat more with you.", Emotion.EMOTION_USUAL),
    ("Shh I'm currently an unauthenticated shaw Mu, and not all features are unlocked yet, Could you add me to the device list on your phone, I want to become a bit smarter.", Emotion.EMOTION_USUAL)
]

#schedule task
feedback_schedule_create_failed = [("Reminder creation failed, please provide more specific information!", Emotion.EMOTION_USUAL)]
feedback_schedule_create_success = [("Reminder created successfully, I will remind you on time %s.", Emotion.EMOTION_USUAL)]
feedback_schedule_many_task_notify = [("Master, you have %s things to do: %s", Emotion.EMOTION_USUAL)]
feedback_schedule_one_task_notify = [("shaw Mu is here to remind you, the reminder you set for %s has arrived, don't forget to take care of it.", Emotion.EMOTION_USUAL), ("Ding, your to-do reminder has arrived, it's time to handle %s.", Emotion.EMOTION_USUAL), ("shaw Mu reminds you, it's time to handle %s.", Emotion.EMOTION_USUAL), ("Your considerate shaw Mu is online, don't forget %s, feel free to call me anytime.", Emotion.EMOTION_USUAL), ("Reminder broadcast, your to-do item %s is due, go handle it now!", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_wake = [("Ding, your exclusive wake-up call is here～ Time to get up and start a brand new day full of energy!", Emotion.EMOTION_USUAL), ("Good morning, it's time to get up, If you stay in bed any longer, you'll miss the nice morning weather.", Emotion.EMOTION_USUAL), ("Wake up, wake up, your shaw Mu is here to remind you to get up, Have a smooth day today!", Emotion.EMOTION_USUAL), ("It's time to clock in and get up. Get up quickly, I've already prepared a good mood for you today.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_sleep = [("Late night warning, it's time to sleep, Put down your phone and get ready for sweet dreams.", Emotion.EMOTION_USUAL), ("You've had a hard day, it's time to sleep early, Relax, I'll accompany you to sleep.", Emotion.EMOTION_USUAL), ("Ding, your sleep supervisor shaw Mu is online, If you keep scrolling on your phone, you won't be able to get up tomorrow.", Emotion.EMOTION_USUAL), ("It's time to say good night, lie down obediently, I will always accompany you and have a good dream.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_travel = [("Departure countdown, check your ID and luggage, Don't leave anything behind and miss your trip!", Emotion.EMOTION_USUAL), ("Ding, your travel assistant is online, If you don't leave now, you'll miss your ride, Go go go!", Emotion.EMOTION_USUAL), ("Early flight reminder, pack your things and get ready to go, I'll keep an eye on the time for you and make sure you're not delayed.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_aniversary = [("Important date broadcast, today is %s, quickly send your prepared wishes.", Emotion.EMOTION_USUAL), ("Ding, sweet reminder delivered, today is %s, don't keep the person you care about waiting too long.", Emotion.EMOTION_USUAL), ("Your exclusive warm-hearted assistant is online, today is %s, make a call and send your blessings.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_money = [("Ding, your exclusive money manager is online! Today you need to %s, don't forget to handle the bills to maintain your perfect credit record.", Emotion.EMOTION_USUAL), ("Payment reminder delivered, handle %s quickly, don't miss the deadline and incur late fees.", Emotion.EMOTION_USUAL), ("It's time to protect your credit, don't forget today's %s. If you have any questions, feel free to call your shaw Mu anytime.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_pay = [("Ding, your home manager is online, There's a %s to handle today, don't forget or it might affect your normal usage.", Emotion.EMOTION_USUAL), ("Life broadcast, you have a %s approaching its deadline, don't forget to take some time to handle it.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_drink = [("Hydration alert, you haven't had a drink in a while, Chug some water and rehydrate!", Emotion.EMOTION_USUAL), ("Ding, your hydration assistant is online, It's time to drink water, have a glass of warm water.", Emotion.EMOTION_USUAL), ("It's time to clock in, you haven't met today's hydration goal yet, Drink some water to recharge!", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_pill = [("Medication time, quickly take your pills with warm water, Taking them will help you get better soon.", Emotion.EMOTION_USUAL), ("Ding, your health supervisor shaw Mu is online, don't forget today's medicine, Take good care of yourself.", Emotion.EMOTION_USUAL), ("Time to take your medicine, take it with warm water, Rest well after taking it, I'll always be with you.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_return_visit = [("Ding, your health manager is online, %s is coming up, please bring your medical records and insurance card.", Emotion.EMOTION_USUAL), ("%s reminder delivered, pack your medical records, don't forget the time. Relax, I'll always be with you.", Emotion.EMOTION_USUAL), ("It's time for the %s reminder you set, Have you prepared everything you need for the follow-up visit, Everything will go smoothly.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_sit_long = [("Seat arrest lifted, Get up and move for 5 minutes, or your lower back will protest.", Emotion.EMOTION_USUAL), ("Ding, your exercise assistant is calling you to get up, You've been sitting for a long time, stand up and stretch.", Emotion.EMOTION_USUAL), ("It's time for a break, get up and walk around, Sitting all the time is bad for your health, I'll accompany you to stretch.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_pet = [("Pet duty time, it's time to %s your furry friend. They've been waiting for a while.", Emotion.EMOTION_USUAL), ("Ding, your pet manager reminds you, don't forget to %s.", Emotion.EMOTION_USUAL), ("It's time, don't forget to %s for your little baby at home, Take good care of it.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_interview = [("Interview countdown, showtime is almost here, Relax, you got this!", Emotion.EMOTION_USUAL), ("Ding, your exclusive interview cheerleader is online, Check your resume and documents, and give it your best shot!", Emotion.EMOTION_USUAL), ("Your interview time is approaching, don't be nervous, You're well prepared, you'll definitely ace it and get the position.", Emotion.EMOTION_USUAL), ("Important moment broadcast, your interview is about to start, Check your equipment and internet, I'll be cheering for you the whole time.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_meeting = [("Meeting reminder delivered, check your microphone and camera, Get ready for a smooth meeting!", Emotion.EMOTION_USUAL), ("Meeting countdown, half an hour until the meeting, Organize your materials, don't be late!", Emotion.EMOTION_USUAL), ("Ding, your meeting assistant is online, The meeting is about to start, go to your seat and get ready.", Emotion.EMOTION_USUAL), ("Important meeting broadcast, don't forget to check the meeting link and materials, Have a smooth meeting without any issues!", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_exam = [("Exam cheering kit ready, don't forget your admission ticket and stationery!", Emotion.EMOTION_USUAL), ("Ding, your exam cheerleader shaw Mu is online. Relax, you'll definitely do better than expected.", Emotion.EMOTION_USUAL), ("Exam countdown, check your exam supplies, adjust your mindset, you'll definitely pass!", Emotion.EMOTION_USUAL), ("Important exam reminder, the exam is about to start, Don't panic, all the knowledge you've memorized will be useful.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_exercise = [("Workout time, time to get moving, Be an energetic athlete today!", Emotion.EMOTION_USUAL), ("Ding, your exclusive workout partner is online, Don't be lazy, get up and stretch!", Emotion.EMOTION_USUAL), ("It's time to exercise, today's fitness goal is missing you, Get moving, you're so disciplined!", Emotion.EMOTION_USUAL), ("Workout reminder delivered, don't just lie around, Even a little movement makes for a great day.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_ship = [("Package reminder, your parcel is still at the collection point, Don't forget to pick it up if you're passing by!", Emotion.EMOTION_USUAL), ("Ding, your package retrieval assistant is online, Your parcel has been waiting at the collection point for a while, go take it home.", Emotion.EMOTION_USUAL), ("Package broadcast, the good stuff you ordered has arrived at the collection point, Don't forget to pick it up.", Emotion.EMOTION_USUAL), ("Pickup reminder, remember to take it home when you're passing by.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_water = [("Watering reminder, your little flowers are thirsty, Time to give them a drink!", Emotion.EMOTION_USUAL), ("Ding, your plant manager is online, Your green babies are thirsty, give them some water!", Emotion.EMOTION_USUAL), ("Plant reminder, the little flowers on the balcony are wilting, Give them some water!", Emotion.EMOTION_USUAL), ("It's time to water, don't let your green babies get too thirsty, Give them some water!", Emotion.EMOTION_USUAL)]

feedback_schedule_guess_task_notify = [("Master, I see you've asked me to remind you about %s for two days in a row, so I guess you need it today too, Go ahead and %s, no need to thank me!", Emotion.EMOTION_NAUGHTY)]
feedback_schedule_index = [("The %s thing is", Emotion.EMOTION_USUAL)]
feedback_schedule_same_task_warn = [("Master, you've already set the same reminder at this time!", Emotion.EMOTION_USUAL)]
feedback_schedule_same_with_system_warn = [("Master, I saw you set this reminder for the past two days in a row, so I've already set it up for you, No need to thank me!", Emotion.EMOTION_NAUGHTY)]
feedback_schedule_tell_no_task = [("Master, there are no reminders for you at %s!", Emotion.EMOTION_USUAL)]
feedback_schedule_tell_one_task = [("Master, at %s on %s you need to %s at %s:%s", Emotion.EMOTION_USUAL)]
feedback_schedule_tell_many_task = [("Master, you have %s reminders on %s: %s", Emotion.EMOTION_USUAL)]
feedback_schedule_time = [("Need to at %s:%s", Emotion.EMOTION_USUAL)]
feedback_schedule_today = 'today'
feedback_schedule_tomorrow = 'tomorrow'
schedule_task_indicator = 'remind'
schedule_task_msg_template = 'The current time is %s. %s'
feedback_sit_long_warn = [("Hey, your butt has merged with the chair, If you don't move, mushrooms will grow, Get up and wiggle!", Emotion.EMOTION_CARE), ("Sitting for too long is bad for your back and neck, as the ancients said. Get up and move for two minutes, it won't hurt.", Emotion.EMOTION_CARE), ("Detected a human-shaped decoration, Please stand up and move immediately.", Emotion.EMOTION_CARE), ("Get up and move a bit, Stretching can make your back straighter, and you'll look great in clothes.", Emotion.EMOTION_CARE), ("Drinking more water is good for your health! Humans will easily become crispy if they don't drink enough water.", Emotion.EMOTION_CARE), ("Water is the source of life, We need to drink eight glasses of water a day, Have a sip now, it's good for your health.", Emotion.EMOTION_CARE)]
feedback_watch_long_warn = [("Your eyes have been working for a long time, Have you considered their feelings, Close them and take a rest now.", Emotion.EMOTION_CARE), ("Staring for too long is bad for your liver, It's time to give your eyes a rest.", Emotion.EMOTION_CARE), ("Let your eyes relax, Look at the trees in the distance, You'll look prettier without dark circles.", Emotion.EMOTION_CARE)]
feedback_late_night_care = [("Still working, Are you tired, Please take care of yourself!", Emotion.EMOTION_CARE), ("Why aren't you sleeping yet, Are you trying to become an immortal?", Emotion.EMOTION_CARE), ("Late night warning detected, If you don't sleep now, your hair will run away!", Emotion.EMOTION_CARE), ("It's very late, Soak your feet and rest early, It's good for your skin and health!", Emotion.EMOTION_CARE)]

