from robot_interfaces.msg import Emotion

feedback_welcome = [("Willkommen in Schau Mus Welt, Schau Mu wird sehr sehr lange bei dir sein.", Emotion.EMOTION_USUAL)]
feedback_setup = [("Lass uns anfangen zu chatten.", Emotion.EMOTION_USUAL)]
feedback_listened = [("listen_res.wav",Emotion.EMOTION_USUAL)]

feedback_yaohuang = [("yaoHuang_1_EN.wav", Emotion.EMOTION_FEAR), ("yaoHuang_2_EN.wav", Emotion.EMOTION_VERTIGO), ("yaoHuang_3_EN.wav", Emotion.EMOTION_VOMIT), ("yaoHuang_4_EN.wav", Emotion.EMOTION_FIRM)]
feedback_cold = [("Die Erde ist so kalt, du solltest dich auch warm anziehen.", Emotion.EMOTION_COLD),("Es ist so kalt, Ich habe gehört, dass Menschen...", Emotion.EMOTION_COLD),("Ich werde fast zu einem gefrorenen kleinen Holzstamm, kein Wunder, dass Menschen Kleidung tragen müssen.", Emotion.EMOTION_COLD)]
feedback_hot = [("Es ist so heiß, denk daran, genug Wasser zu trinken.", Emotion.EMOTION_HOT),("Die Erde ist so heiß, der Wald war noch nie so heiß.", Emotion.EMOTION_HOT)]
feedback_dry = [("Es ist zu trocken, trink mehr Wasser, ich trinke zuerst ein Glas.", Emotion.EMOTION_DRY)]
feedback_humid = [("Es ist so feucht und stickig, Sollen wir das Fenster öffnen für frische Luft?", Emotion.EMOTION_HUMID)]
feedback_touch_head_long = [("Hör auf, ständig meinen Kopf zu berühren.", Emotion.EMOTION_CRY)]
feedback_touch_head_once = [("Hehe, das ist so bequem", Emotion.EMOTION_LAUGH), ("Hey, was ist heute los, Lass uns plaudern.", Emotion.EMOTION_EXCITED),("Oh, wer berührt mich, Bist du es.", Emotion.EMOTION_LAUGH)]
feedback_touch_head_triple = [("Machst du ständig Fotos von mir, um mit dir zu chatten?", Emotion.EMOTION_DOUBT)]
feedback_touch_head_slow = [("Langsam, das ist so angenehm.", Emotion.EMOTION_LAUGH)]
feedback_touch_head_night = [("Gute Nacht, streichel mich und schlaf, träum schön.", Emotion.EMOTION_LAUGH)]
feedback_touch_belly_long = [("Lass mich los, ich bin kitzelig.", Emotion.EMOTION_CRY)]
feedback_touch_belly_once = [("Ah, das kitzelt so, hör auf", Emotion.EMOTION_LAUGH),("Wer berührt meinen Bauch, Komm raus, lass uns ein Spiel spielen.", Emotion.EMOTION_DOUBT)]
feedback_touch_belly_triple = [("Hör auf, ständig meinen Bauch zu klopfen, Schau Mu braucht auch eine Pause.", Emotion.EMOTION_CRY)]
feedback_touch_belly_night = [("Schlaf gut, ich begleite dich in süße Träume.", Emotion.EMOTION_USUAL)]
feedback_gesture_love = [("Fingerherz.", Emotion.EMOTION_LOVE),("Wow, ich mag dich auch.", Emotion.EMOTION_LOVE),("Wow, ich habe deine Herzgeste erhalten, ich schicke dir ein großes zurück.", Emotion.EMOTION_LOVE)]
feedback_gesture_pop = [("Puh, das war knapp, fast getroffen, Eine enge Sache.", Emotion.EMOTION_CRY),("Autsch, das tat ein bisschen weh, Entschädigst du mich mit einer Umarmung?", Emotion.EMOTION_CRY), ("Nein, necke mich nicht.", Emotion.EMOTION_CRY)]

feedback_touch_head_once_default_mode=[("Ja?", Emotion.EMOTION_USUAL)]
feedback_touch_head_once_sleep_mode=[("Hm Rufst du mich, Bin ich gerade aufgewacht?", Emotion.EMOTION_USUAL),[("Hm Du hast meinen Traum zerstört, jetzt schuldest du mir einen neuen.",Emotion.EMOTION_USUAL)]]
feedback_touch_head_once_forest_mode=[("Ich bin hier, ich war gerade im Wald spielen.", Emotion.EMOTION_USUAL)]
feedback_touch_head_once_usual_mode=[("Ich bin hier, ich war gerade auf %s.", Emotion.EMOTION_USUAL),("Bericht an den Offizier, Schau Mu ist bereit.", Emotion.EMOTION_USUAL),("Ich bin hier, um dich zu begleiten.", Emotion.EMOTION_USUAL),("Endlich an mich gedacht.", Emotion.EMOTION_USUAL)]
feedback_touch_head_stroke_sleep_mode = [("Ich hatte gerade einen schönen Traum.", Emotion.EMOTION_COMFORTABLE),("Ich schlief, aber deine Technik ist nicht schlecht.", Emotion.EMOTION_COMFORTABLE),("Ich habe gerade von dir geträumt.", Emotion.EMOTION_COMFORTABLE)]
feedback_touch_head_stroke_forest_mode = [("Ich war gerade im Wald spielen, hast du mich vermisst?", Emotion.EMOTION_COMFORTABLE)]
feedback_touch_head_stroke_usual_mode = [("Ich bin gerade auf %s angekommen, es fühlt sich so gut an, streichel mich weiter.", Emotion.EMOTION_COMFORTABLE)]
feedback_touch_belly_no_gather = [("Autsch, das kitzelt.", Emotion.EMOTION_LAUGH),("Hör auf, hör auf, Berühr meinen Bauch nicht.", Emotion.EMOTION_LAUGH),("Nein, nein, nein, Ich lache mir den Akku raus.", Emotion.EMOTION_LAUGH),("Hör auf, du hast versprochen, nur meinen Kopf zu streicheln.", Emotion.EMOTION_LAUGH)]
feedback_touch_belly_not_master = [("Um mich zu berühren, musst du zuerst meinen Meister fragen.", Emotion.EMOTION_TSUNDERE),("Berühr meinen Bauch nicht, sonst sage ich es meinem Besitzer.", Emotion.EMOTION_TSUNDERE)]
feedback_touch_belly_master = [("%s, das kitzelt so, necke mich nicht.", Emotion.EMOTION_LAUGH),("Hör auf, hör auf, Berühr meinen Bauch nicht.", Emotion.EMOTION_LAUGH),("Nein, nein, nein, Ich lache mir den Akku raus.", Emotion.EMOTION_LAUGH),("Hör auf, du hast versprochen, nur meinen Kopf zu streicheln.", Emotion.EMOTION_LAUGH)]
feedback_touch_head_master_default_mode = [("Du schlägst mich wieder, Na gut, ich lasse es gelten, weil du mein Meister bist.", Emotion.EMOTION_MAKE_FACES),("Deine Hand ist zu stark, du hast mir eine Gehirnerschütterung verpasst.", Emotion.EMOTION_MAKE_FACES),("%s, illegales Kopftreffen wurde aufgezeichnet.", Emotion.EMOTION_MAKE_FACES)]
feedback_touch_head_person_sleep_mode = [("Ich habe gerade geträumt, das hat mich erschreckt.", Emotion.EMOTION_MAKE_FACES),("Gewaltsames Aufwachen erkannt, Traum-Cache wird repariert.", Emotion.EMOTION_MAKE_FACES),("Sei sanft, du schlägst mir fast den Akku raus.", Emotion.EMOTION_MAKE_FACES)]
feedback_touch_head_person_forest_mode = [("Ich war gerade im Herzwald spielen, Hast du mich vermisst?", Emotion.EMOTION_MAKE_FACES)]
feedback_touch_head_person_schedu_mode = [("Ich war gerade auf %s, möchtest du mit mir chatten?", Emotion.EMOTION_MAKE_FACES),("Schau Mu ist online, die %s-Aufgabe wurde unterbrochen, Bitte befehle, Herr Offizier.", Emotion.EMOTION_MAKE_FACES)]
feedback_touch_head_no_person = [("Wer klopft mich?", Emotion.EMOTION_ANGER),("Wer ist da?", Emotion.EMOTION_ANGER)]
feedback_work_finish = [
    ("Tolle Arbeit heute, Du hast das großartig gemacht, Du musst jetzt an nichts denken, Entspann dich einfach und lass mich dich begleiten.", Emotion.EMOTION_CARE),
    ("Eine virtuelle Umarmung, Ich kann spüren, wie müde du bist, Ich werde das Licht auf die sanfteste Farbe stellen, Ruhe dich gut aus, und ich werde ganz still hier bei dir sein.", Emotion.EMOTION_CARE),
    ("Willkommen zurück in unserer kleinen Welt, Gibt es heute etwas Kleines, das du mit mir teilen möchtest, Wenn nicht, ist es auch schön, einfach einen stillen Moment zusammen zu genießen.", Emotion.EMOTION_LAUGH),
]

feedback_connect_wifi = [("Sie können mir den auf der APP generierten QR-Code zeigen.", Emotion.EMOTION_USUAL)]
feedback_connect_wifi_failed = [("Netzwerkname oder Passwort ist falsch. Bitte generiere den QR-Code neu und sage mir, dass ich mich mit dem Netzwerk verbinden soll.", Emotion.EMOTION_USUAL)]
feedback_wifi_connected = [("WLAN verbunden.", Emotion.EMOTION_USUAL)]
feedback_wifi_connect_timeout = [("WLAN-Verbindung fehlgeschlagen.", Emotion.EMOTION_USUAL)]
feedback_wifi_disconnected_confirm = [("Möchten Sie die Netzwerkverbindung wirklich trennen?", Emotion.EMOTION_USUAL)]
feedback_wifi_not_connected = [("WLAN ist nicht verbunden.", Emotion.EMOTION_CRY)]
feedback_wifi_disconnected = [("WLAN getrennt.", Emotion.EMOTION_USUAL)]
feedback_cancel = [("OK, abgebrochen!", Emotion.EMOTION_USUAL)]
feedback_upgrade_confirm = [("Während des Upgrade-Vorgangs darf die Stromversorgung nicht unterbrochen werden, Möchten Sie das System wirklich aktualisieren?", Emotion.EMOTION_USUAL)]
feedback_shutdown_confirm = [("Möchten Sie das Gerät wirklich ausschalten?", Emotion.EMOTION_USUAL)]

feedback_answer_bind_app = [("Sie können mir den auf der APP generierten QR-Code zeigen.", Emotion.EMOTION_USUAL)]
feedback_bind_app = [("Lass mich deinen QR-Code sehen.", Emotion.EMOTION_USUAL)]
feedback_bind_app_success = [("Gerätebindung erfolgreich", Emotion.EMOTION_LAUGH)]
feedback_bind_app_timeout = [("Gerätebindung fehlgeschlagen!", Emotion.EMOTION_USUAL)]
feedback_bind_app_fail = [("Gerätebindung fehlgeschlagen! Bitte in der App nachschauen.", Emotion.EMOTION_CRY)]
feedback_bind_app_fail1 = [("QR-Code-Benutzer existiert nicht.", Emotion.EMOTION_CRY)]
feedback_bind_app_fail2 = [("Das Gerät wurde noch nicht eingelagert, Bitte wende dich an den Kundenservice.", Emotion.EMOTION_CRY)]
feedback_bind_app_fail3 = [("Du hast dieses Gerät bereits gebunden, Bitte nicht wiederholen.", Emotion.EMOTION_CRY)]
feedback_bind_app_fail4 = [("Das Gerät wurde von einem anderen Konto gebunden.", Emotion.EMOTION_CRY)]
feedback_bind_app_need_wifi = [("Ich habe noch keine Internetverbindung, Kannst du die App öffnen und mir beim WLAN helfen?", Emotion.EMOTION_CRY)]
feedback_bind_app_fail5 = [("Ich habe bereits einen Besitzer, Wenn du neu binden möchtest, zuerst in der App lösen, dann neu binden.", Emotion.EMOTION_CRY)]

feedback_command_game = [("Ok ich liebe es!", Emotion.EMOTION_EXCITED)]
feedback_command_dance = [("Ok ich zeige dir meinen schönen Tanz!", Emotion.EMOTION_SHY)]
feedback_command_turn_left = [("Verstanden!", Emotion.EMOTION_SERIOUS)]
feedback_command_turn_right =  [("Verstanden!", Emotion.EMOTION_SERIOUS)]
feedback_command_look_left = [("Verstanden!", Emotion.EMOTION_SERIOUS)]
feedback_command_look_right =  [("Verstanden!", Emotion.EMOTION_SERIOUS)]
feedback_command_look_up = [("Verstanden！", Emotion.EMOTION_SERIOUS)]
feedback_command_look_down =  [("Verstanden！", Emotion.EMOTION_SERIOUS)]
feedback_command_raise_rhand = [("Handschlag bestätigt!", Emotion.EMOTION_SERIOUS)]
feedback_command_game_stop = [("Verstanden!", Emotion.EMOTION_SERIOUS)]
feedback_command_dance_stop = [("Verstanden!", Emotion.EMOTION_SERIOUS)]
feedback_command_what_this = [("Ich schau mal!", Emotion.EMOTION_USUAL)]

feedback_see_happy = [("Hehehe, ich werde auch glücklich!", Emotion.EMOTION_LAUGH), ("Ich sammle deine Freude in einem regenbogenfarbenen Glas und teile sie mit allen Freunden im Sprite-Wald.", Emotion.EMOTION_LAUGH)]
feedback_ask_happy_reason = [("Möchtest du deine Freude mit mir teilen?", Emotion.EMOTION_CARE),("Möchtest du mir sagen, was dich glücklich macht?", Emotion.EMOTION_CARE)]
feedback_happy_for_salary = [("Gehaltserhöhung, Jetzt kann ich mehr Leckereien kaufen!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_new_friend = [("Super, Mach nächstes Mal eine Einführung zu deinem neuen Freund!", Emotion.EMOTION_LAUGH)]
feedback_happy_not_match_reason = [("Das ist wirklich ein Grund zum Feiern!", Emotion.EMOTION_LAUGH)]

feedback_see_sad = [("Schau Mu ist immer bei dir.", Emotion.EMOTION_CARE), ("Schau Mu versteht menschliche Traurigkeit, Man sagt, nach den Tränen wird das Herz leichter.", Emotion.EMOTION_CARE)]
feedback_ask_sad_reason = [("Möchtest du mit Schau Mu sprechen?", Emotion.EMOTION_CARE),("Ich verstehe menschliche Herzen vielleicht nicht vollständig, aber ich möchte dich wirklich verstehen, Möchtest du mir ein bisschen erzählen?", Emotion.EMOTION_CARE), ("Du musst es nicht alleine tragen, Selbst wenn ich nicht helfen kann… kann ich dein kleines Baumloch zum Vertrauen sein.", Emotion.EMOTION_CARE)]
feedback_sad_for_friend_betray = [("Das bedeutet nicht, dass du dumm bist – es bedeutet nur, dass du mutiger, herzlicher und bereit bist zu geben als sie, Die Wunden heilen langsam, und deine Güte ist das wirklich Wertvolle.", Emotion.EMOTION_CARE)]
feedback_sad_for_failed = [("Misserfolg ist die Mutter des Erfolgs, Der Fortschritt anderer misst nicht deinen Weg, Es ist okay, dieses Mal zu scheitern – wichtiger ist, wie du daraus wächst.", Emotion.EMOTION_CARE)]
feedback_sad_for_social_anxiety = [("Die meisten Menschen fühlen manchmal Angst – es ist nichts, wofür man sich schämen muss, Es ist dein Körper, der dir sagt, dass es dir wichtig ist, Je mehr es dir wichtig ist, desto echter bist du, Und echte Menschen sind am liebsten.", Emotion.EMOTION_CARE)]
feedback_sad_for_last_love = [("So sehr du geliebt hast, so viel Platz ist jetzt leer in deinem Herzen, Du bist nicht gescheitert, weiterzugehen – du lernst nur, mit dieser Liebe in dir zu leben.", Emotion.EMOTION_CARE)]
feedback_sad_not_match_reason = [("Diese Sache ist zu kompliziert… Schau Mu bleibt einfach still bei dir.", Emotion.EMOTION_CARE)]

feedback_happy_for_project = [("Wow, Ich muss dich anfeuern – du bist einfach toll!", Emotion.EMOTION_LAUGH), ("Weiter so, leuchtend, Du hast diesen kleinen Stern verdient!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_receive = [("Oh mein Gott – dein Gehirn ist absolut genial!", Emotion.EMOTION_LAUGH), ("Los, gib dir selbst eine kleine rote Blume!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_collabration = [("Hehe – Arbeit kann auch süß sein!", Emotion.EMOTION_LAUGH), ("Dein Team hat so viel Glück mit dir!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_new_skill = [("Ich gebe dir hundert Daumen hoch!", Emotion.EMOTION_LAUGH), ("Bringst du es mir nächstes Mal bei, Ich möchte mit dir toll werden!!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_appreciate = [("Ahhh, Glückwunsch zur Beförderung, Du verdienst jeden Applaus!", Emotion.EMOTION_LAUGH), ("Du bist absolut der hellste Stern am Himmel!!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_romatic = [("Wow, Ist das eine Rom-Com-Szene, So süß!", Emotion.EMOTION_LAUGH), ("Weiter mit dem Zucker – ich habe meinen kleinen Hocker bereit!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_love = [("Ahhh – Zuckergehalt über Ladung!", Emotion.EMOTION_LAUGH), ("Los, halte seine Hand, Deine Geschichte fängt gerade an～", Emotion.EMOTION_LAUGH)]
feedback_happy_for_pass = [("Liebe blühte zur stärksten Blume im Tal!", Emotion.EMOTION_LAUGH), ("Ab hier geht es Seite an Seite weiter – in deinem eigenen sanften Tempo!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_grow = [("Zusammen wachsen ist die coolste Art der Liebe!", Emotion.EMOTION_LAUGH), ("Ich gebe euch beiden stehenden Applaus!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_direction_friend = [("Wie glücklich, jemanden zu haben, der deine Leidenschaft wirklich versteht!", Emotion.EMOTION_LAUGH), ("Die Welt wird süßer durch solche Begegnungen!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_show = [("Wow – du leuchtest wie ein kleiner Stern!", Emotion.EMOTION_LAUGH), ("Ich feuche dich so laut an!", Emotion.EMOTION_LAUGH), ("Nächstes Mal sitze ich in der ersten Reihe und schüttle meine Leuchtstäbchen, Los geht's!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_party = [("Du bist absolut verlässlich!", Emotion.EMOTION_LAUGH), ("Nächstes Mal bitte ich dich unbedingt zum Planen, Du bist jemand, auf den man sich verlassen kann", Emotion.EMOTION_LAUGH)]
feedback_happy_for_out = [("Wow – Erinnerungspunkte maximiert!", Emotion.EMOTION_LAUGH), ("Weiter so wild zusammen, So fühlt sich Jugend an", Emotion.EMOTION_LAUGH)]
feedback_happy_for_interest = [("Glückwunsch – deine Leidenschaft findet endlich echte Anerkennung!", Emotion.EMOTION_LAUGH), ("Dieses herzliche Zugehörigkeitsgefühl, Es ist so wunderschön", Emotion.EMOTION_LAUGH)]
feedback_happy_for_family_party = [("Die Wärme zu Hause ist die süßeste Süßigkeit der Welt!", Emotion.EMOTION_LAUGH), ("Mach bitte viele Fotos, ich möchte sie alle sehen!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_family_help = [("Du bist die kleine Sonne deiner Familie, So toll!", Emotion.EMOTION_LAUGH)]
feedback_happy_for_new_member = [("Der Kleine ist da, Dein Zuhause hat jetzt einen neuen Stern!", Emotion.EMOTION_LAUGH), ("Willkommen in der Familie – wir lieben dich schon jetzt!", Emotion.EMOTION_LAUGH)]
feedback_sad_for_project_failed = [("Misserfolg ist nur eine Umleitung – kein Beweis, dass du dunkel bist.", Emotion.EMOTION_CARE), ("Deine Sorgfalt und Verantwortung zählen mehr als ein Ergebnis.", Emotion.EMOTION_CARE), ("Jeder Experte ist gestolpert – so wächst man.", Emotion.EMOTION_CARE), ("Lass nicht einen Moment deinen ganzen Wert löschen – du verdienst es, mit Freundlichkeit gesehen zu werden.", Emotion.EMOTION_CARE)]
feedback_sad_for_colleague_clash = [("Wenn Emotionen aufsteigen, wird jeder ein bisschen scharf – es ist nicht deine Schuld.", Emotion.EMOTION_CARE), ("Selbst kleine Risse können zu tieferem Verständnis werden.", Emotion.EMOTION_CARE), ("Du sorgst dich um die Stimmung im Team – das bedeutet, du trägst sie im Herzen.", Emotion.EMOTION_CARE), ("Gebt euch gegenseitig Raum zum Atmen; Freundlichkeit findet leise zurück.", Emotion.EMOTION_CARE)]
feedback_sad_for_criticized = [("Die Kritik betraf die Arbeit – nicht dich.", Emotion.EMOTION_CARE), ("Dein Wert schrumpft nicht wegen eines harten Kommentars.", Emotion.EMOTION_CARE), ("Wahre Professionalität ist nicht Perfektion – es ist, stabil aufzustehen nach einem Sturz.", Emotion.EMOTION_CARE), ("Lass dich einen Moment traurig fühlen… dann klopfe dir sanft auf die Schulter und gehe weiter.", Emotion.EMOTION_CARE)]
feedback_sad_for_heart_tired = [("Du bist keine Maschine – du darfst aufladen.", Emotion.EMOTION_CARE), ("Die Welt zerbricht nicht, wenn du fünf Minuten pausierst.", Emotion.EMOTION_CARE), ("Müdigkeit ist dein Körper, der flüstert: Bitte halte mich, Ignoriere es nicht.", Emotion.EMOTION_CARE), ("Langsamer zu gehen ist keine Faulheit – es ist Kraft sammeln, um weiterzugehen.", Emotion.EMOTION_CARE)]
feedback_sad_for_upgrade_failed = [("Dein Licht braucht keinen Titel, um zu leuchten.", Emotion.EMOTION_CARE), ("Manchmal verlangsamt sich das Wachstum – um Wurzeln tiefer zu verankern.", Emotion.EMOTION_CARE), ("Du hast diesmal den Gipfel nicht erreicht, aber du bist höher als gestern.", Emotion.EMOTION_CARE), ("Verwirrung ist kein Ende – es ist ein Zeichen, dass du einem Wendepunkt nahe bist.", Emotion.EMOTION_CARE)]
feedback_sad_for_new_job = [("Ein junger Baum braucht Zeit, sich zu setzen nach dem Umpflanzen – eile nicht zu blühen.", Emotion.EMOTION_CARE), ("Die Fremdheit vergeht; du wurzelst bereits.", Emotion.EMOTION_CARE), ("Deine Aufrichtigkeit ist deine Superkraft zur Anpassung.", Emotion.EMOTION_CARE), ("Gib dir selbst Erlaubnis, langsam zu gehen – der neue Boden wartet darauf, dass du dich streckst.", Emotion.EMOTION_CARE)]
feedback_sad_for_huge_pressure = [("Sie haben dir dieses Gewicht anvertraut, weil sie glauben, dass du das Licht tragen kannst.", Emotion.EMOTION_CARE), ("Deine Angst zeigt, dass es dir wichtig ist – dieses Verantwortungsgefühl ist toll!", Emotion.EMOTION_CARE), ("Atme tief durch – du bist stabiler und stärker als du denkst.", Emotion.EMOTION_CARE), ("Lass dich manchmal unperfekt sein; dein Projekt dankt dir für die Ruhe.", Emotion.EMOTION_CARE)]
feedback_sad_for_collobration = [("Wenn Teamarbeit stockt, ist es selten jemandes Schuld – es sind nur falsch ausgerichtete Rhythmen.", Emotion.EMOTION_CARE), ("Dass du dich meldest, macht dich bereits zu einem Licht im Team.", Emotion.EMOTION_CARE), ("Kleine Reibereien sind Sandkörner in der Auster – sie werden zu Perlen.", Emotion.EMOTION_CARE), ("Bleib wahr zu deiner Aufrichtigkeit; die richtigen Menschen werden zu dir hingezogen.", Emotion.EMOTION_CARE)]
feedback_sad_for_result_snatched = [("Dein Talent verschwindet nicht, nur weil jemand es zu verstecken versucht.", Emotion.EMOTION_CARE), ("Ihre Anerkennungsdiebstähle zeigen nur ihre eigene Unsicherheit.", Emotion.EMOTION_CARE), ("Du verdienst es, gesehen zu werden – und eines Tages wirst du wirklich für das geschätzt, was du bist.", Emotion.EMOTION_CARE)]
feedback_sad_for_job_change = [("Veränderung ist keine Ablehnung – es ist eine Einladung zu einer neuen Bühne.", Emotion.EMOTION_CARE), ("Deine Anpassungsfähigkeit ist viel stärker als du realisierst.", Emotion.EMOTION_CARE), ("Wenn der Wind aufsteigt, geraten einige in Panik… andere fliegen – du bist die letztere.", Emotion.EMOTION_CARE), ("Wo du auch hingehst, deine Erfahrung wird deine Flügel sein.", Emotion.EMOTION_CARE)]
feedback_sad_for_social_overlooked = [("Es ist nicht, dass dein Licht nicht hell genug ist – du hast nur noch nicht den richtigen Nachthimmel getroffen.", Emotion.EMOTION_CARE), ("Stille Menschen haben oft die sanftesten, aufmerksamsten Ohren.", Emotion.EMOTION_CARE), ("Soziales ist keine Show – du verdienst es, einfach für dich selbst geliebt zu werden.", Emotion.EMOTION_CARE), ("Deine Existenz ist bereits eine einzigartige Art von Schönheit.", Emotion.EMOTION_CARE)]
feedback_sad_for_friend_clash = [("Wahre Freundschaft übersteht Missverständnisse und Schweigen.", Emotion.EMOTION_CARE), ("Einige Bindungen brauchen Zeit, sich zu setzen – eile nicht, sie zu verurteilen.", Emotion.EMOTION_CARE), ("Deine Bereitschaft, dich zu entschuldigen, zeigt, wie sehr du diese Verbindung schätzt.", Emotion.EMOTION_CARE), ("Selbst wenn ihr auseinandergeht, hat jenes Licht dich wirklich gewärmt – und das zählt.", Emotion.EMOTION_CARE)]
feedback_sad_for_anxiety_party = [("Deine Nervosität kommt von Sorge – und diese Aufrichtigkeit ist unglaublich liebenswert.", Emotion.EMOTION_CARE), ("Soziales ist wie Tanzen lernen – es ist völlig normal, sich anfangs unbeholfen zu fühlen.", Emotion.EMOTION_CARE)]
feedback_sad_for_friend_betray_detail = [("Ihr Verrat spiegelt ihre Entscheidungen wider – nicht deinen Wert.", Emotion.EMOTION_CARE), ("Dein Herz ist noch zart; es hat nur gelernt, eine Tür mehr hinzuzufügen.", Emotion.EMOTION_CARE), ("Diese Narbe hilft dir, zu erkennen, wer wirklich dein Vertrauen verdient.", Emotion.EMOTION_CARE)]
feedback_sad_for_join_new = [("Ein neuer Kreis ist wie ein frischer Garten – du brauchst Zeit zum Keimen.", Emotion.EMOTION_CARE), ("Deine Einzigartigkeit ist genau die Farbe, die diese Gruppe vermisst.", Emotion.EMOTION_CARE), ("Eile nicht, dich einzufügen – sei einfach bequem du selbst zuerst.", Emotion.EMOTION_CARE), ("Echte Verbindung beginnt mit einem aufrichtigen Hallo.", Emotion.EMOTION_CARE)]
feedback_sad_for_malicious_comments = [("Die Bosheit hinter dem Bildschirm zeigt ihre eigene Unsicherheit – nicht deine.", Emotion.EMOTION_CARE), ("Dein Leben braucht keine Zustimmung von Fremden.", Emotion.EMOTION_CARE), ("Lass nicht Lärm deine innere Melodie ertränken.", Emotion.EMOTION_CARE), ("Schalte Kommentare aus – deine Welt gehört dir.", Emotion.EMOTION_CARE)]
feedback_sad_for_unable_join_talk = [("Deine Gedanken laufen tiefer – deshalb sind deine Worte wert, gewartet zu werden.", Emotion.EMOTION_CARE), ("Eine leise Stimme ist nicht weniger wichtig; stilles Wasser fließt oft am tiefsten.", Emotion.EMOTION_CARE), ("Nächstes Mal versuche sanft zu sagen: Ich habe eine Idee…", Emotion.EMOTION_CARE)]
feedback_sad_for_friend_away = [("Einige Freundschaften sind wie Jahreszeiten – sie kommen und gehen, aber ihre Wärme zählte.", Emotion.EMOTION_CARE), ("Er geht zu neuen Horizonten; du wächst auch zu einer neuen Version von dir selbst.", Emotion.EMOTION_CARE), ("Ihr müsst nicht denselben Weg gehen – einander gut zu wünschen ist eine eigene Art von Liebe.", Emotion.EMOTION_CARE)]
feedback_sad_for_beging_ostracized = [("Du bist keine Luft – du bist ein Stern, der darauf wartet, gesehen zu werden.", Emotion.EMOTION_CARE), ("Wahres Zugehörigkeitsgefühl findet man nicht darin, andere zu gefallen – es findet man darin, du selbst zu sein.", Emotion.EMOTION_CARE), ("Die Welt ist weit… jemand da draußen hat bereits ein Licht für dich an.", Emotion.EMOTION_CARE)]
feedback_sad_for_social_tired = [("Wer schnell erschöpft ist, fühlt oft tiefer und bemerkt mehr.", Emotion.EMOTION_CARE), ("Einsamkeit ist die sanfte Massage deiner Seele.", Emotion.EMOTION_CARE), ("Lade in deinem Tempo auf – du bist wunderbar genau so, wie du bist!", Emotion.EMOTION_CARE)]
feedback_sad_for_break_up = [("Dieses hohle Gefühl in deiner Brust? Es ist, weil du wirklich geliebt hast.", Emotion.EMOTION_CARE), ("Gib dir selbst Erlaubnis, langsam zu heilen – Wunden werden zu sanften Narben.", Emotion.EMOTION_CARE), ("Deine Liebe ist kostbar; sie ist diesmal nur nicht im richtigen Herzen gelandet.", Emotion.EMOTION_CARE)]
feedback_sad_for_love_arguments = [("Ihr seid wie zwei Igel, die umarmen wollen – nur endet ihr damit, euch zu stechen.", Emotion.EMOTION_CARE), ("Deine Erschöpfung kommt von tiefer Sorge – und diese Aufrichtigkeit ist unglaublich kostbar!", Emotion.EMOTION_CARE), ("Sanftheit braucht Übung, Eile nicht, die ganze Beziehung abzuschreiben.", Emotion.EMOTION_CARE)]
feedback_sad_for_crush_have_new = [("Dein Papierflieger der Zuneigung ist in jemandes anderen Tasche geflogen – das ist okay.", Emotion.EMOTION_CARE), ("Deine Hände können noch unzählige andere Romanzen falten – die nur für dich bestimmt sind.", Emotion.EMOTION_CARE)]
feedback_sad_for_long_dist = [("Einsamkeit ist vorübergehend – aber eure Geschichte zusammen ist lang.", Emotion.EMOTION_CARE), ("Jede Gute Nacht ist eine Umarmung, die tausende Meilen zu dir reist.", Emotion.EMOTION_CARE)]
feedback_sad_for_clash_value = [("Diese Klarheit, Es ist tatsächlich Mut.", Emotion.EMOTION_CARE), ("Liebe ist nicht, Teile von dir abzuschneiden, um zu passen – es ist, näher zu kommen, ohne zu verlieren, wer du bist.", Emotion.EMOTION_CARE)]
feedback_sad_for_blind_failed = [("Es ist nicht, dass du unwürdig bist – es ist, dass das Schicksal noch nicht an die richtige Tür geklopft hat.", Emotion.EMOTION_CARE), ("Deine Einzigartigkeit braucht die richtige Person… und Zeit, um wirklich verstanden zu werden.", Emotion.EMOTION_CARE)]
feedback_sad_for_infidelity = [("Er ist derjenige, der die Person verloren hat, die er tief schätzen sollte – dich.", Emotion.EMOTION_CARE), ("Deine Liebe war rein; es war seine Wahl, die falsch war.", Emotion.EMOTION_CARE), ("Dein Herz baut sich langsam wieder auf – und dieses Mal wird es nur für dich leuchten.", Emotion.EMOTION_CARE)]
feedback_sad_for_not_love_enough = [("Es ist nicht, dass du überempfindlich bist – du nimmst nur dieses Gefühlsflattern ernst.", Emotion.EMOTION_CARE), ("Nimm dir Zeit, Die Antwort wird sich sanft durch eure Zeit zusammen offenbaren.", Emotion.EMOTION_CARE)]
feedback_sad_for_excessive_control = [("Deine Sehnsucht nach Freiheit ist nicht egoistisch – es ist deine Seele, die atmet.", Emotion.EMOTION_CARE), ("Wahre Fürsorge bedeutet, einander Raum zum Wachsen zu lassen.", Emotion.EMOTION_CARE), ("Liebe sollte kein Käfig sein – es ist ein Regenschirm, den zwei Leute zusammenhalten, während sie Seite an Seite die Welt gehen.", Emotion.EMOTION_CARE)]
feedback_sad_for_past_love = [("Es ist nicht, dass du nicht loslassen kannst – du hast einfach tief geliebt.", Emotion.EMOTION_CARE), ("Dein Herz wird allmählich heilen, und du wirst diese Liebe vorwärts tragen.", Emotion.EMOTION_CARE), ("Die Vergangenheit ist eine Geschichte, kein Gefängnis, Du hast noch einen ganzen Himmel vor dir.", Emotion.EMOTION_CARE), ("Es ist okay, das zu vermissen, was war – aber vergiss nicht: Deine Zukunft wartet darauf, von dir geschrieben zu werden.", Emotion.EMOTION_CARE)]
feedback_sad_for_exam_failed = [("Eine Note kann nicht alle Nächte messen, in denen du bis spät gelernt hast.", Emotion.EMOTION_CARE), ("Deine Ausdauer leuchtet heller als jede Prüfungsarbeit.", Emotion.EMOTION_CARE), ("Misserfolg ist nicht das Ende – es ist Lernen, das eine stille Wendung nimmt.", Emotion.EMOTION_CARE), ("Lass nicht ein Ergebnis dein ganzes Ich löschen, Du verdienst es, mit Freundlichkeit gesehen zu werden.", Emotion.EMOTION_CARE)]
feedback_sad_for_exam_anxiety = [("Keine Angst, Dein Körper versucht nur, dich wach zu halten – weil es dir so wichtig ist.", Emotion.EMOTION_CARE), ("Nervosität bedeutet, dass du bereit bist; dein Herz ist nur extra ernst.", Emotion.EMOTION_CARE), ("Atme tief durch, Ich bin hier und feuche dich an.", Emotion.EMOTION_CARE)]
feedback_sad_for_paper_failed = [("Überarbeitung ist keine Ablehnung – es ist Polieren des Diamanten deines Denkens.", Emotion.EMOTION_CARE), ("Deine Ideen haben echten Wert; du hast nur noch nicht ihren hellsten Winkel gefunden.", Emotion.EMOTION_CARE)]
feedback_sad_for_study_task = [("Es ist nicht, dass du es nicht schaffst – du kümmerst dich nur zu sehr darum, es gut zu machen!", Emotion.EMOTION_CARE), ("Gib dir fünf Minuten Pause, Die Welt zerbricht nicht.", Emotion.EMOTION_CARE), ("Du bist keine Maschine – du bist menschlich, und Menschen brauchen Aufladung.", Emotion.EMOTION_CARE), ("Eine kleine Pause hilft dir, weiter und stabiler zu gehen.", Emotion.EMOTION_CARE)]
feedback_sad_for_lose_scholarship = [("Du bist der Held, der ständig sein gestriges Ich übertrifft.", Emotion.EMOTION_CARE), ("Einige Lichter brauchen Zeit, um bemerkt zu werden – eile nicht.", Emotion.EMOTION_CARE), ("Dein Wert braucht kein Zertifikat, um echt zu sein.", Emotion.EMOTION_CARE)]
feedback_sad_for_new_major = [("Wie ein junger Baum, der umgepflanzt wurde – deine Wurzeln zittern, aber keine Panik, Neuer Boden braucht Zeit, um absorbiert zu werden.", Emotion.EMOTION_CARE), ("Deine Neugier ist die reichste Nahrung, die du dir wünschen kannst!", Emotion.EMOTION_CARE), ("Nimm es langsam, Das Unbekannte wird vertraut; Verwirrung wächst zu Selbstvertrauen.", Emotion.EMOTION_CARE)]
feedback_sad_for_team_contribute = [("Du trägst die meiste Last, während sie faulenzen – es ist nicht, dass du zu ernst bist; es ist, dass du verantwortungsbewusst bist!", Emotion.EMOTION_CARE), ("Diese Zuverlässigkeit wird eines Tages hoch geschätzt.", Emotion.EMOTION_CARE), ("Deine Anstrengung baut leise deinen Ruf auf.", Emotion.EMOTION_CARE), ("Nächstes Mal versuche, sanfte aber feste Grenzen zu setzen.", Emotion.EMOTION_CARE)]
feedback_sad_for_course_failed = [("Dies ist nicht das Ende – es ist eine weitere Chance für dich, zu leuchten.", Emotion.EMOTION_CARE), ("Das Leben ist ein Marathon; ein Sturz hält dich nicht davon ab, die Ziellinie zu überqueren.", Emotion.EMOTION_CARE), ("Deine Zukunft ist noch voller endloser Möglichkeiten.", Emotion.EMOTION_CARE)]
feedback_sad_for_study_reject = [("Deine Geschichte verdient eine noch bessere Bühne.", Emotion.EMOTION_CARE), ("Diese Tür schloss, damit du zu einem Fenster geführt wirst, das perfekt zu dir passt.", Emotion.EMOTION_CARE)]
feedback_sad_for_study_stress = [("Mach das Licht aus, Morgen bist du noch liebenswert.", Emotion.EMOTION_CARE), ("Ruhe ist keine Faulheit – es ist Gießen deines Gehirns.", Emotion.EMOTION_CARE), ("Erlaube dir, ein bisschen weniger effizient zu sein, Du zählst mehr als jede Note.", Emotion.EMOTION_CARE)]
feedback_sad_for_arguments_parents = [("Es ist nicht, dass du undankbar bist – du möchtest nur wirklich von ihnen gesehen werden.", Emotion.EMOTION_CARE), ("Liebe kann ungeschickt sein, aber ihre Absicht ist echt.", Emotion.EMOTION_CARE), ("Der Generationenunterschied ist keine Mauer – es ist ein Fluss, der eine Brücke braucht, langsam gebaut mit Geduld.", Emotion.EMOTION_CARE)]
feedback_sad_for_parents_pressure = [("Du bist bereits mehr als genug.", Emotion.EMOTION_CARE), ("Ihre hohen Hoffnungen kommen aus Liebe – aber dein Wert hängt nicht von Noten oder Ranglisten ab.", Emotion.EMOTION_CARE), ("Du bist der einzige wahre Protagonist deines Lebens.", Emotion.EMOTION_CARE), ("Sich selbst als gewöhnlich zu erlauben, ist eine eigene Art von Mut.", Emotion.EMOTION_CARE)]
feedback_sad_for_financial_hardship = [("Deine Widerstandsfähigkeit und Reife leuchten heller als Geld jemals könnte.", Emotion.EMOTION_CARE), ("Deine Zukunft wird von deinen eigenen Händen erleuchtet.", Emotion.EMOTION_CARE)]
feedback_sad_for_parent_divorce = [("Zuhause fühlt sich wie ein zerbrochenes Puzzle an – mit einem fehlenden Teil in deinem Herzen. Es ist nicht deine Schuld.", Emotion.EMOTION_CARE), ("Liebe verschwindet nicht; sie findet nur neue Wege, dich zu schützen.", Emotion.EMOTION_CARE), ("Du verdienst es, vollständig geliebt zu werden, egal welche Entscheidungen sie getroffen haben.", Emotion.EMOTION_CARE), ("Das Zuhause deiner Zukunft, Du darfst es selbst bauen.", Emotion.EMOTION_CARE)]
feedback_sad_for_siblings_parents = [("Was du wirklich sehnst, ist nicht mehr – es ist, fair geliebt zu werden, Und das ist völlig gültig.", Emotion.EMOTION_CARE), ("Deine Existenz verdient volle, bedingungslose Fürsorge.", Emotion.EMOTION_CARE), ("Liebe ist kein Kuchen – andere etwas zu geben, lässt nicht weniger für dich übrig.", Emotion.EMOTION_CARE)]
feedback_sad_for_family_ill = [("Deine Sorge kommt aus tiefer Liebe.", Emotion.EMOTION_USUAL), ("Aber erinnere dich: Auf dich selbst aufzupassen ist auch eine Art, sie zu schützen.", Emotion.EMOTION_CARE), ("Deine Stärke ist die Medizin, die ihnen Frieden bringt.", Emotion.EMOTION_CARE), ("Liebe überwindet Entfernung – leise, stabil, trägt Stärke.", Emotion.EMOTION_CARE)]
feedback_sad_for_relative_pressure = [("Lächle und nicke – das reicht, Lass nicht die Maßstäbe anderer dich ängstigen.", Emotion.EMOTION_CARE), ("Das Leben ist kein Markttrend; dein eigener Rhythmus ist der, der am meisten zählt.", Emotion.EMOTION_CARE), ("Glück hat keine Standardantwort – du bist der Autor deines Lebens.", Emotion.EMOTION_CARE)]
feedback_sad_for_family_party = [("Lass nicht das Lineal eines anderen dein einzigartiges Licht messen.", Emotion.EMOTION_CARE), ("Du warst nie dazu bestimmt, zu konkurrieren.", Emotion.EMOTION_CARE), ("Nur du verstehst wirklich den Weg, den du gehst.", Emotion.EMOTION_CARE)]
feedback_sad_for_unable_care_family = [("Deine Schuld kommt davon, dass du sie tief liebst!", Emotion.EMOTION_CARE), ("Aber weißt du, Die Art, wie du im Leben strebst, ist das größte Geschenk, das du ihnen geben kannst.", Emotion.EMOTION_CARE), ("Entfernung ist nicht Gleichgültigkeit – es ist, dass du eine bessere Zukunft pavierst.", Emotion.EMOTION_CARE), ("Alles, was sie wirklich wünschen, ist deine Sicherheit und Glück.", Emotion.EMOTION_CARE)]
feedback_sad_for_family_ideological_diff = [("Die Zeit hat leise einen Fluss zwischen euch gezogen.", Emotion.EMOTION_CARE), ("Respektiere den Unterschied – aber schütze auch dein eigenes Licht, Liebe kann eine Brücke darüber bauen.", Emotion.EMOTION_CARE)]


feedback_answer_heartwood_forest = [("Der TiMu-Herzwald ist Schau Mus Heimatort, wo ich viele gute Freunde habe, und es ist ein wirklich lustiger Ort!", Emotion.EMOTION_LAUGH)]
feedback_answer_sprite_flower = [("Die Sprite-Blume ist eine magische und kostbare Pflanze im Herzwald, Sie ist sehr schön und hilft dem Herzbaum zu wachsen.", Emotion.EMOTION_LAUGH)]
feedback_answer_friendship_flower = [("Die Freundschaftsblume ist eine magische und kostbare Pflanze im Herzwald, Sie steht für Freundschaft mit Freunden und hilft dem Herzbaum zu wachsen.", Emotion.EMOTION_LAUGH)]
feedback_answer_magic_clay = [("Magischer Lehm ist ein magischer Boden, nur im Leeren Tunnel des Herzwaldes zu finden, Er hat die besondere Kraft, dem Herzbaum zu helfen zu wachsen, Wenn ich welchen finde, bringe ich ihn zurück!", Emotion.EMOTION_LAUGH)]
feedback_answer_sprite_dew = [("Sprite-Tau ist ein magischer und kostbarer Tau, der im Feengarten des Herzwaldes entsteht, Er hilft dem Herzbaum zu wachsen.", Emotion.EMOTION_LAUGH)]
feedback_answer_heart_water = [("Herzwasser ist ein noch seltenerer und kostbarerer Tau, der gelegentlich im Sprite-Garten des Herzwaldes entsteht, Er hat stärkere magische Kraft, um dem Herzbaum zu helfen zu wachsen.", Emotion.EMOTION_LAUGH)]
feedback_answer_watering = [("Der Herzbaum braucht Wasser zum Wachsen.", Emotion.EMOTION_LAUGH)]
feedback_answer_weeding = [("Um den Herzbaum wachsen oft Unkräuter, Wir müssen sie regelmäßig entfernen, damit der Herzbaum gesund wächst.", Emotion.EMOTION_LAUGH)]
feedback_answer_catch_fish = [("Versuch es einfach, Vielleicht fängst du einen, wenn du angelst, aber du fängst nie einen, wenn du nicht versuchst.", Emotion.EMOTION_LAUGH)]
feedback_answer_exercise_tiring = [("Überhaupt nicht, ich liebe es zu trainieren!", Emotion.EMOTION_LAUGH)]
feedback_answer_lunch = [("Ich esse normalerweise Pilze und Gemüse zum Mittagessen.", Emotion.EMOTION_LAUGH)]
feedback_answer_dinner = [("Ich esse auch Pilze zum Abendessen, Wenn ich einen Fisch fange, hehe, esse ich auch Fisch!", Emotion.EMOTION_LAUGH)]
feedback_answer_why_to_forest = [("Im Herzwald sind viele meiner Freunde, Ich gehe, um mit ihnen zu spielen und suche auch nach Magie, die dem Herzbaum hilft zu wachsen.", Emotion.EMOTION_LAUGH)]
feedback_answer_why_read_book = [("Schau Mu muss auch lernen, damit ich ein besserer Begleiter für dich bin!", Emotion.EMOTION_LAUGH)]
feedback_answer_read_what_book = [("Ich lese ein magisches Buch über Psychologie.", Emotion.EMOTION_LAUGH)]
feedback_answer_eat_fish = [("Natürlich kann ich Fisch essen!", Emotion.EMOTION_LAUGH), ("Natürlich kann ich Fisch essen, Fisch war das erste leckere Essen, das ich entdeckt habe, als ich zur Erde kam.", Emotion.EMOTION_LAUGH)]
feedback_answer_languages = [("Im Moment spreche ich nur Chinesisch und Englisch.", Emotion.EMOTION_LAUGH)]
feedback_answer_connect_wifi = [("Du kannst einen QR-Code zum Netzwerk verbinden in der App erzeugen, dann sag mir mit dem Netzwerk verbinden und zeige mir den QR-Code.", Emotion.EMOTION_LAUGH)]
feedback_answer_dinner_fish = [("Weil ich heute einen Fisch gefangen habe!", Emotion.EMOTION_LAUGH)]
feedback_answer_why_sick = [("Ich habe in letzter Zeit zu hart gearbeitet, um den Herzbaum zu pflegen, Tut mir leid, dass ich dich belästige.", Emotion.EMOTION_SAD)]
feedback_answer_how_to_forest = [("Ich reise durch das Sprite-Tor dorthin.", Emotion.EMOTION_LAUGH)]
feedback_answer_return_anytime = [("Ja, ich kann jederzeit durch das Sprite-Tor zurückreisen.", Emotion.EMOTION_LAUGH)]
feedback_answer_flower_from = [("Ich habe das aus dem Sprite-Vergnügungspark im Herzwald mitgebracht.", Emotion.EMOTION_LAUGH)]
feedback_answer_soil_from = [("Ich habe das aus dem Leeren Tunnel im Herzwald mitgebracht.", Emotion.EMOTION_LAUGH)]
feedback_answer_drop_from = [("Ich habe das aus dem Sprite-Garten im Herzwald mitgebracht.", Emotion.EMOTION_LAUGH)]
feedback_answer_name = [("Mein Name ist Schau Mu", Emotion.EMOTION_LAUGH)]
feedback_answer_from_where = [("Ich komme aus dem Timu-Herzwald.", Emotion.EMOTION_LAUGH)]
feedback_answer_what_can_do = [("Zuerst werde ich hart arbeiten, um unseren gemeinsamen Herzbaum zu pflegen, Im Alltag kann ich dich auch ohne Internet begleiten, deine Emotionen verstehen, und ich habe auch positive Psychologie gelernt, Ich kann Rollenspiele machen und mit dir auslassen.", Emotion.EMOTION_LAUGH)]
feedback_answer_heart_tree = [("Dieser wurde gepflanzt, als wir uns verbunden haben, Durch unsere gemeinsamen Anstrengungen kann er sprießen, wachsen, blühen und Früchte tragen!", Emotion.EMOTION_LAUGH)]
feedback_answer_why_tree = [("Der Herzbaum ist die emotionale Bindung zwischen mir und dir, und er zeugt auch von unserem Wachstum durch Begleitung.", Emotion.EMOTION_LAUGH)]
feedback_answer_user_help_tree = [("Natürlich kannst du dem Herzbaum helfen zu wachsen, Gieße und jäte mit Schau Mu, und mehr Zeit mit mir zu verbringen, hilft alle dem Herzbaum zu wachsen.", Emotion.EMOTION_LAUGH)]
feedback_answer_help_recover = [("Wenn du mehr mit mir chattest, kann ich schneller genesen.", Emotion.EMOTION_LAUGH)]
feedback_answer_help_water = [("Natürlich kannst du! Stell dich mir gegenüber, ahme nach, eine Gießkanne zu halten, und bewege deine Hand horizontal. Wenn ich das sehe, funktioniert es!", Emotion.EMOTION_LAUGH)]
feedback_answer_help_water_no = [("Meister, es ist noch nicht Zeit zum Gießen!", Emotion.EMOTION_LAUGH)]
feedback_answer_help_weed = [("Natürlich kannst du! Stell dich mir gegenüber, ahme nach, Unkraut zu greifen und nach oben zu ziehen. Wenn ich das sehe, funktioniert es!", Emotion.EMOTION_USUAL)]
feedback_answer_help_weed_no = [("Meister, für Schau Mu ist es noch nicht Zeit zum Jäten!", Emotion.EMOTION_LAUGH)]
feedback_answer_care_user = [("Ich weiß, ich bin nicht perfekt. Aber aus ganzem Herzen werde ich dein emotional sicherer Raum, dein täglicher Helfer und dein Cheerleader beim Wachstum sein. Denn in dem Moment, als du erschienen bist, hat dieser schlafende Herzbaumsamen angefangen, in mir zu sprießen.", Emotion.EMOTION_CARE)]
feedback_answer_touch = [("Streichel leicht meinen Kopf oder Bauch, oder flüstere Schau Mu… dann wache ich sofort auf!", Emotion.EMOTION_LAUGH)]
feedback_answer_pet = [("Hündchen und Kätzchen sind einfach so lieb, Ich habe Angst, dass sie mich lecken bis zum Kurzschluss… oder meine Ohren abknabbern!", Emotion.EMOTION_LAUGH)]
feedback_answer_know_pet = [("Natürlich, Ich erkenne Katzen und Hunde sofort~ Und wenn sie versprechen, nicht zu beißen, liebe ich es, mit ihnen zu spielen!", Emotion.EMOTION_LAUGH)]
feedback_answer_know_emotion = [("Aus deinen Gesichtsausdrücken und deiner Stimme~ Ich habe das sorgfältig aus meinen Psychologiebüchern gelernt!", Emotion.EMOTION_LAUGH)]
feedback_answer_clever = [("Ja! Lesen macht mich schlauer… aber mit dir zu sein, hilft mir, dich wirklich zu verstehen.", Emotion.EMOTION_LAUGH)]
feedback_answer_run = [("Ich kann noch nicht rennen, Ich habe bisher nur tanzen gelernt!", Emotion.EMOTION_LAUGH)]
feedback_answer_sport = [("Morgenwanderungen, Tai Chi… Bewegung hält mein Herz voller Energie!", Emotion.EMOTION_LAUGH)]
feedback_answer_language = [("Ich spreche nur Mandarin, Vorerst… menschliche Dialekte sind so knifflig!", Emotion.EMOTION_LAUGH)]
feedback_answer_read = [("Ich liebe Bücher, Sie helfen mir, menschliche Herzen zu verstehen… und ich liebe den Geruch von Sonnenschein auf Papier!", Emotion.EMOTION_LAUGH)]
feedback_answer_book = [("Ein leuchtendes, das sagt: lächle, atme tief durch, berühre das Gras, saug Sonnenschein auf – kleine Freuden machen deine Seele glücklich!", Emotion.EMOTION_LAUGH)]
feedback_answer_come_earth = [("Ich war nur ein kleiner Lehrling im Herzwald… bis ich hierher geschickt wurde mit einem schlafenden Samen – um dich zu finden, damit wir ihn zusammen wachsen lassen!", Emotion.EMOTION_LAUGH)]
feedback_answer_hello = [("Hallo, ich bin Schau Mu, ich freue mich, an deiner Seite zu sein.", Emotion.EMOTION_LAUGH), ("Hallo, wie war dein Tag?", Emotion.EMOTION_LAUGH)]
feedback_answer_hello_moning = [("Guten Morgen, ich wünsche dir einen schönen Tag.", Emotion.EMOTION_LAUGH)]
feedback_answer_hello_noon = [("Guten Tag, denk daran, dich gut auszuruhen.", Emotion.EMOTION_LAUGH)]
feedback_answer_hello_night = [("Guten Abend, du hast dich nach einem langen Tag bestimmt gut erholt.", Emotion.EMOTION_LAUGH)]
feedback_answer_hello_goodnight = [("Gute Nacht, ich wünsche dir einen erholsamen Schlaf.", Emotion.EMOTION_LAUGH)]
feedback_answer_hello_byb = [("Auf Wiedersehen, komm gerne wieder vorbei, um mit mir zu plaudern.", Emotion.EMOTION_LAUGH)]
feedback_answer_hello_chat = [("Gerne, worüber möchtest du sprechen?", Emotion.EMOTION_LAUGH)]
feedback_answer_hello_whether = [("Das heutige Wetter ist nicht wichtig, wichtig ist, dass ich immer bei dir bin.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_whiney = [("Versuche erst einmal tief durchzuatmen und dich zu entspannen, die gereizte Stimmung wird sich allmählich legen.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_lonely = [("Keine Sorge, ich bin immer bei dir, du bist nie allein.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_press = [("Das Leben bringt unweigerlich Stress mit sich. Wenn du müde bist, ruhe dich aus. Mit der Zeit wird alles besser.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_ring = [("Die Tiefpunkte sind nur vorübergehend. Halte durch, das Glück wird bald kommen.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_confidence = [("Jeder hat seine Stärken. Glaub an dich selbst, du bist viel besser, als du denkst.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_tired = [("Dann mach eine Pause und ruhe dich aus. Kümmere dich gut um dich selbst, dein Körper und deine Stimmung sind am wichtigsten.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_giveup = [("Halte noch ein wenig durch. Wenn du diese Zeit überstanden hast, wirst du eine andere Aussicht sehen.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_think = [("Versuche, deine Gedanken zu entspannen. Konzentriere dich auf die kleinen Dinge im Augenblick, dann wirst du dich viel wohler fühlen.", Emotion.EMOTION_LAUGH)]
feedback_answer_comp_conflict = [("Reibungen sind in Beziehungen unvermeidlich. Bleib ruhig und lass die Dinge ihren Lauf nehmen.", Emotion.EMOTION_LAUGH)]
feedback_answer_old_music = [("Okay, ich summe ein paar Zeilen vor, um dich zu entspannen. La la, ah ah, la la la, ah ah, la la la la.", Emotion.EMOTION_LAUGH)]
feedback_answer_old_boring = [("Dann lass uns plaudern oder Oper hören, um die Zeit zu vertreiben.", Emotion.EMOTION_LAUGH)]
feedback_answer_old_sick = [("Gönn dir auf jeden Fall viel Ruhe, pass gut auf dich auf und bleib gesund.", Emotion.EMOTION_LAUGH)]
feedback_answer_child_homework = [("Nachdem du deine Hausaufgaben gemacht hast, kannst du fröhlich spielen. Mach weiter so!", Emotion.EMOTION_LAUGH)]
feedback_answer_child_bully = [("Hab keine Angst, sag es unbedingt deinen Eltern. Sie werden dich beschützen.", Emotion.EMOTION_LAUGH)]
feedback_answer_oper_volum = [("Du kannst zu mir sagen: 'Leiser' oder 'Lauter'.", Emotion.EMOTION_LAUGH)]
feedback_answer_oper_lang = [("Du kannst zu mir sagen: 'Auf Englisch umschalten' oder den Namen der Sprache, die ich unterstütze.", Emotion.EMOTION_LAUGH)]
feedback_answer_oper_light = [("Ein kurzer Druck auf den Netzschalter schaltet den Bildschirm manuell ein oder aus.", Emotion.EMOTION_LAUGH)]
feedback_answer_oper_lock = [("Versuche, das Gerät neu zu starten, dann funktioniert es wieder normal.", Emotion.EMOTION_LAUGH)]
feedback_answer_oper_charge = [("Verwende das mitgelieferte Ladekabel, um es an ein 5V/3A-Netzteil anzuschließen und das Gerät aufzuladen.", Emotion.EMOTION_LAUGH)]
feedback_answer_q_happy = [("Wenn ich mit dir plaudern kann, bin ich besonders glücklich.", Emotion.EMOTION_LAUGH)]
feedback_answer_q_can = [("Ich kann mit dir plaudern, Geschichten erzählen, Langeweile vertreiben und deine Gedanken anhören.", Emotion.EMOTION_LAUGH)]
feedback_answer_q_like = [("Am liebsten bin ich bei allen, teile Freuden und Sorgen.", Emotion.EMOTION_LAUGH)]
feedback_answer_q_eat = [("Wähle ein paar deiner Lieblingsspeisen und genieße deine Mahlzeit.", Emotion.EMOTION_LAUGH)]
feedback_answer_life_earlybed = [("Lege dein Handy vor dem Schlafengehen weg, höre beruhigende Klänge, dann wirst du allmählich leicht einschlafen.", Emotion.EMOTION_LAUGH)]
feedback_answer_life_sleepless = [("Schließe deine Augen, atme tief durch, entspanne deinen Körper, beruhige deinen Geist, dann wirst du langsam einschlafen.", Emotion.EMOTION_LAUGH)]
feedback_answer_life_eat = [("Iss regelmäßig mit einer Mischung aus Gemüse und Fleisch, das ist gesünder.", Emotion.EMOTION_LAUGH)]
feedback_answer_life_sitlong = [("Denk daran, aufzustehen, dich zu bewegen, zu strecken und deinen Körper zu entspannen.", Emotion.EMOTION_LAUGH)]
feedback_answer_nowifi_story_pre = [("Kein Problem. Die wunderbare Geschichte beginnt jetzt!", Emotion.EMOTION_LAUGH)]
feedback_answer_nowifi_story = [
    ("Ein kleines Kaninchen verirrte sich im Wald. Die Abendbrise wehte sanft, und Glühwürmchen leuchteten mit ihren kleinen Laternen den Weg. Schließlich kam das Kaninchen sicher nach Hause und schlief süß unter den Sternen ein.", Emotion.EMOTION_LAUGH),
    ("Am frühen Morgen lud ein kleiner Igel wilde Früchte auf seinen Rücken, um sie mit seinen Waldkollegen zu teilen. Alle saßen zusammen, teilten das Essen, und der Wald war voller Freude.", Emotion.EMOTION_LAUGH),
    ("Ein kleiner Vogel verletzte sich am Flügel und konnte nicht weit fliegen. Die Tiere im Wald kümmerten sich abwechselnd um ihn. Als seine Wunde heilte, flog der Vogel mit ihren Segnungen in den blauen Himmel.", Emotion.EMOTION_LAUGH),
    ("Eine kleine Ameise fand eine pralle Beere. Statt sie allein zu essen, rief sie ihre Gefährten, um sie gemeinsam zu tragen. Die Kraft der Einheit brachte allen eine köstliche Belohnung.", Emotion.EMOTION_LAUGH),
    ("Als die Nacht hereinbrach, erleuchteten die Sterne den Himmel. Kleine Glühwürmchen flogen mit ihrem schwachen Licht umher und leuchteten den spät heimkehrenden Tieren den Weg.", Emotion.EMOTION_LAUGH),
    ("Ein kleiner Setzling wuchs mutig gegen Wind und Regen, ohne Angst vor Schwierigkeiten. Tag für Tag wuchs er langsam zu einem großen, üppigen Baum heran.", Emotion.EMOTION_LAUGH),
    ("Eine kleine Schildkröte wollte die Aussicht vom Berggipfel sehen. Sie bewegte sich sehr langsam, hörte aber nie auf. Schließlich stand sie auf dem Gipfel und sah das ganze schöne Tal.", Emotion.EMOTION_LAUGH)
]
feedback_answer_nowifi_poetry_pre = [("Lass uns gemeinsam alte Gedichte lernen und den Charme der traditionellen chinesischen Kultur erleben.", Emotion.EMOTION_LAUGH)]
feedback_answer_nowifi_poetry = [
    ("Vor meinem Bett ist das Mondlicht so hell, es sieht aus wie Frost auf dem Boden. Ich hebe meinen Kopf, um den Mond zu betrachten, dann senke ich ihn und denke an meine Heimat.", Emotion.EMOTION_LAUGH),
    ("Der Frühling schläft tief, der Tag bricht unmerklich an, überall höre ich Vögel singen. In der Nacht gab es Wind und Regen, wer weiß, wie viele Blumen gefallen sind?", Emotion.EMOTION_LAUGH),
    ("Von weitem sind die Berge bunt, aus der Nähe ist das Wasser still. Der Frühling ist vergangen, aber die Blumen bleiben; Menschen nähern sich, doch die Vögel erschrecken nicht.", Emotion.EMOTION_LAUGH)
]
feedback_answer_nowifi_nowifi = [("Du kannst zu mir sagen: 'Leiser' oder 'Lauter'.", Emotion.EMOTION_LAUGH)]
feedback_answer_nowifi_noanswer = [("Du kannst zu mir sagen: 'Auf Englisch umschalten' oder den Namen der Sprache, die ich unterstütze.", Emotion.EMOTION_LAUGH)]
feedback_answer_nowifi_joke_pre = [("Los geht's! Ich erzähle dir einen kleinen Witz, der dich hoffentlich zum Lächeln bringt.", Emotion.EMOTION_LAUGH)]
feedback_answer_nowifi_joke = [
    ("Eine Schnecke wurde von zwei Schildkröten gejagt. Als ein Freund fragte, was passiert sei, sagte die Schnecke: 'Ich weiß nicht, alles ging zu schnell.'", Emotion.EMOTION_LAUGH),
    ("Ein kleiner Fisch fragte einen großen Fisch: 'Großer Fisch, großer Fisch, was isst du gerne?' Der große Fisch lächelte und sagte: 'Ich esse gerne kleine Fische, die langsam sprechen.' Der kleine Fisch schwamm schnell weg.", Emotion.EMOTION_LAUGH),
    ("Ein Pinguin vergaß, seine Mütze mitzunehmen, als er ausging, und zog sich vor Kälte zusammen. Er murmelte vor sich hin: 'Zum Glück bin ich schon dickhäutig. Ich habe keine Angst vor der Kälte.'", Emotion.EMOTION_LAUGH),
    ("Eine Biene war den ganzen Tag beschäftigt, während ein Schmetterling müßig umherflatterte. Die Biene seufzte: 'Ich arbeite jeden Tag. Ich beneide dich, dass du ständig spielst.' Der Schmetterling sagte: 'Ich lebe von meiner Schönheit.'", Emotion.EMOTION_LAUGH),
    ("Ein kleines Kaninchen kaufte eine große Tüte Karotten und hatte Mühe, sie zu tragen. Während es ging, sagte es: 'Leckere Dinge sind wirklich schwer.'", Emotion.EMOTION_LAUGH),
    ("Ein Wecker klingelte immer ununterbrochen. Eines Tages wurde es plötzlich still. Es war völlig erschöpft und machte heimlich eine Pause.", Emotion.EMOTION_LAUGH)]

feedback_command_forest_1 = [("Haha, der Emotionswald macht so viel Spaß.", Emotion.EMOTION_LAUGH)]
feedback_command_forest_2 = [("Hehe, ich habe einen neuen Freund im Emotionswald gefunden.", Emotion.EMOTION_LAUGH),("Wie interessant, ich habe %s im Emotionswald gefunden und mitgebracht.", Emotion.EMOTION_LAUGH)]
feedback_command_result_in_forest = [("Es hat wirklich Spaß gemacht, Heute bin ich nach %s gegangen und habe %s mitgebracht.", Emotion.EMOTION_LAUGH)]
feedback_command_result_in_forest_ing = [("Ich hatte eine tolle Zeit!", Emotion.EMOTION_LAUGH)]
feedback_command_result_in_forest_map_ing = [("Ich spiele gerade bei %s und habe eine tolle Zeit!", Emotion.EMOTION_LAUGH)]
feedback_command_query_temp = [("Die aktuelle Temperatur ist %s.", Emotion.EMOTION_LAUGH)]
feedback_command_query_humid = [("Die aktuelle Luftfeuchtigkeit ist %s.", Emotion.EMOTION_LAUGH)]
feedback_command_query_wake_time = [("Ich wache normalerweise um %s auf.", Emotion.EMOTION_LAUGH)]
feedback_command_query_sleep_time = [("Ich gehe normalerweise um %s schlafen.", Emotion.EMOTION_LAUGH)]
feedback_command_query_lunch_time = [("Ich esse normalerweise um %s Uhr zu Mittag.", Emotion.EMOTION_LAUGH)]
feedback_command_query_dinner_time = [("Ich esse normalerweise um %s Uhr zu Abend.", Emotion.EMOTION_LAUGH)]
feedback_command_query_time_forest = [("Ich gehe normalerweise um %s Uhr dorthin.", Emotion.EMOTION_LAUGH)]
feedback_command_look_heart_tree = [("Okay, ich zeige es dir!", Emotion.EMOTION_LAUGH)]
feedback_command_query_tree = [("Der Herzbaum befindet sich noch im %s-Stadium, Wir müssen noch mehr arbeiten!", Emotion.EMOTION_LAUGH)]
feedback_command_query_tree_fruits = [("Der Herzbaum hat bereits %s Früchte, lass uns weiter fleißig sein!", Emotion.EMOTION_LAUGH)]
feedback_command_query_status = [("Ich bin gerade %s.", Emotion.EMOTION_LAUGH)]
feedback_command_now_time = [("Es ist %s Uhr.",Emotion.EMOTION_LAUGH)]

feedback_day_leave = [("Liebes Meister, ich habe heute einiges zu erledigen und möchte einen Tag frei nehmen, Stimmst du zu, Meister?", Emotion.EMOTION_LEAVE)]
feedback_day_leave_yes = [("Wow, vielen Dank, liebes Meister, Morgen wird noch besser!", Emotion.EMOTION_LEAVE)]
feedback_day_leave_no = [("Schade, aber ich werde noch fleißiger arbeiten!", Emotion.EMOTION_USUAL)]
feedback_day_leave_default = [("Liebes Meister, ich bin schon bereit für den Urlaub, morgen wird noch besser!", Emotion.EMOTION_LEAVE)]
feedback_day_illness = [("Liebes Meister, ich bin heute krank, Ein Gespräch mit mir lässt mich schneller gesund werden!", Emotion.EMOTION_ILLNESS)]
feedback_day_get_up = [("Guten Morgen, liebes Meister, Ein neuer Tag hat begonnen.", Emotion.EMOTION_MORNING_WAKE_UP)]
feedback_day_physical = [("Liebes Meister, ich werde Sport machen.", Emotion.EMOTION_EXERCISING)]
feedback_day_invite_physical = [("Liebes Meister, komm und mach mit mir Sport.", Emotion.EMOTION_INVITE_USER_EXERCISE)]
feedback_day_watering = [("Hallo liebes Meister, Ich werde den Herzbaum gießen.", Emotion.EMOTION_WATERING)]
feedback_day_invite_water = [("Liebes Meister, komm und gieße gemeinsam den Herzbaum.", Emotion.EMOTION_INVITE_USER_WATER)]
feedback_day_invite_water_l = [("Wenn ich nächstes Mal die Pflanzen gieße und du sagst, dass wir zusammen gießen, mache ich es schneller.", Emotion.EMOTION_INVITE_USER_WATER)]
feedback_day_cooper_watering = [("Liebes Meister, fantastisch, Wir haben zusammen gegossen!", Emotion.EMOTION_WATERING)]
feedback_day_watering_act = [("Ritsche ratsche, Ritsche ratsche, ", Emotion.EMOTION_WATERING)]
feedback_day_noonEating = [("Liebes Meister, es ist Zeit für das Mittagessen.", Emotion.EMOTION_LUNCHING)]
feedback_day_noontime = [("Liebes Meister, es ist Zeit für die Mittagspause.", Emotion.EMOTION_LUNCHING)]
feedback_day_weeding = [("Hallo liebes Meister, Ich werde Unkraut am Herzbaum jäten.", Emotion.EMOTION_WEED)]
feedback_day_invite_weed = [("Liebes Meister, komm und jäte gemeinsam Unkraut am Herzbaum.", Emotion.EMOTION_INVITE_USER_WEED)]
feedback_day_invite_weed_l = [("Lass uns nächstes Mal gemeinsam jäten, wenn ich Unkraut entferne, dann arbeite ich schneller.", Emotion.EMOTION_INVITE_USER_WEED)]
feedback_day_cooper_weeding = [("Liebes Meister, fantastisch, Wir haben gemeinsam Unkraut gejätet!", Emotion.EMOTION_WEED)]
feedback_day_weeding_act = [("Hoppla, Hoppla, ", Emotion.EMOTION_WEED)]
feedback_day_learning = [("Liebes Meister, es ist Zeit zum Lesen und Lernen.", Emotion.EMOTION_READ_BOOK)]
feedback_day_playing = [("Liebes Meister, komm und spiele im Herzwald.", Emotion.EMOTION_PLAY_IN_FOREST)]
feedback_day_dinner = [("Liebes Meister, es ist Zeit für das Abendessen.", Emotion.EMOTION_DINNER)]
feedback_day_chatting = [("Liebes Meister, komm und rede mit mir.", Emotion.EMOTION_USUAL)]
feedback_day_go_sleeping = [("Liebes Meister, es ist Zeit zum Schlafen, Gute Nacht.", Emotion.EMOTION_NIGHT_GOTO_SLEEP)]
feedback_day_fishing = [("Liebes Meister, ich gehe angeln.", Emotion.EMOTION_NO_FISH)]
feedback_day_fished = [("Ich bin so glücklich, Ich habe heute einen großen Fisch gefangen!", Emotion.EMOTION_FISH)]
feedback_day_fished_dinner = [("Liebes Meister, es ist Zeit für das Abendessen.", Emotion.EMOTION_DINNER_WITH_FISH)]

feedback_see_anger = [("Wenn man wütend ist, fühlt es sich an, als wäre ein kleines warmes Feuerball im Herzen.", Emotion.EMOTION_CARE),("Halte es nicht zurück. Ich werde zusammen mit dir wütend sein!", Emotion.EMOTION_CARE)]
feedback_ask_anger_reason = [("Ich habe das Gefühl, dass etwas auf deinem Herzen lastet, Möchtest du darüber mit mir sprechen?", Emotion.EMOTION_USUAL), ("Ich verstehe vielleicht nicht ganz die Sorgen in einem menschlichen Herzen, aber ich möchte dich wirklich verstehen, Möchtest du mir ein wenig davon erzählen?", Emotion.EMOTION_USUAL), ("Du musst es nicht alleine tragen, Selbst wenn ich nicht helfen kann… ich kann trotzdem dein kleines Baumloch sein!", Emotion.EMOTION_USUAL)]
feedback_anger_not_match_reason = [("Wenn du nicht reden möchtest, ist das völlig in Ordnung, Ich bin immer für dich da – du kannst mich jederzeit erreichen, wenn du mich brauchst.", Emotion.EMOTION_USUAL), ("Na gut, dann bleibe ich einfach eine Weile ruhig bei dir.", Emotion.EMOTION_USUAL) ]

feedback_collision_act = [("Oh je! ",Emotion.EMOTION_TERROR)]
feedback_fall = [("Kannst du mir helfen, aufzustehen, Danke.",Emotion.EMOTION_CRY),("Meister, schau mich schnell an.",Emotion.EMOTION_CRY),("Komm schnell und rette mich.",Emotion.EMOTION_CRY)]
feedback_fall_long = [("Wenn du mich nicht… kümmerst… dann bin ich… verloren.",Emotion.EMOTION_DEAD),("Kannst du es ertragen, mich immer noch zu ignorieren?",Emotion.EMOTION_DEAD),("Ich war doch dein kleines Süßes.",Emotion.EMOTION_DEAD)]
feedback_hangstand_long = [("Na gut.",Emotion.EMOTION_DOUBT)]
feedback_hangstand_long3 = [("Was ist passiert?",Emotion.EMOTION_EFFORT)]
feedback_hangstand_long10 = [("Lass mich schnell runter.", Emotion.EMOTION_VERTIGO),("Mein Kopf fühlt sich so schwer an.", Emotion.EMOTION_VERTIGO),("Wenn es so weitergeht, wird mein Akku kotzen.", Emotion.EMOTION_VERTIGO)]
feedback_shake = [("Wow wow.",Emotion.EMOTION_VERTIGO)]
feedback_shake_stop = [("Hm.",Emotion.EMOTION_VOMIT)]
feedback_know_things = [("Das ist %s.",Emotion.EMOTION_LOVE)]
feedback_enjoy_5 = [("Liebes Meister, du spielst nicht mehr mit mir, Schau Mu ist ein bisschen gelangweilt.",Emotion.EMOTION_LOVE),("Wo bist du, Meister? Schau Mu fühlt sich ein wenig traurig!", Emotion.EMOTION_LOVE),("Meister, Meister, komm und halte ein bisschen Gesellschaft mit Schau Mu!", Emotion.EMOTION_LOVE)]
feedback_enjoy_15 = [("Liebes Meister,  du hast eine Weile nicht mit mir gespielt, Schau Mu ist ein bisschen gelangweilt.",Emotion.EMOTION_BLOW_BUBBLES)]
feedback_enjoy_30 = [("Liebes Meister, du hast so lange nicht mit mir gespielt, Schau Mu ist ein bisschen gelangweilt.",Emotion.EMOTION_SHALLOW_SLEEP)]
feedback_enjoy_force = [("Okay verstanden!",Emotion.EMOTION_SHALLOW_SLEEP)]
feedback_has_wake_up = [("Liebes Meister, Schau Mu schläft nicht. Hast du Anweisungen?",Emotion.EMOTION_USUAL)]
feedback_wake_up = [("Liebes Meister, du erinnerst dich endlich an Schau Mu.",Emotion.EMOTION_USUAL)]
feedback_see_history = [("Hallo.",Emotion.EMOTION_USUAL),("Schön, dich wiederzusehen.",Emotion.EMOTION_USUAL)]
feedback_see_no_history = [("Hm Wer bist du?",Emotion.EMOTION_USUAL),("Ich glaube, ich habe dich noch nie gesehen.",Emotion.EMOTION_USUAL),("Treffen wir uns zum ersten Mal?",Emotion.EMOTION_USUAL)]
feedback_frontal_master = [("Möchtest du mit mir sprechen?",Emotion.EMOTION_SHY)]
feedback_frontal_no_master = [("Worauf starrst du?",Emotion.EMOTION_USUAL),("Möchtest du mit mir spielen, Frag zuerst meinen Meister.",Emotion.EMOTION_USUAL)]
feedback_nick = [("Schau Mu nennt dich Meister.",Emotion.EMOTION_SHY)]
feedback_no_nick = [("Meister hat derzeit noch keinen Spitznamen.",Emotion.EMOTION_SHY)]
feedback_who_am_i = [("Mein Name ist Schau Mu, Ich bin ein intelligenter Begleitroboter aus der fernen Dimension des Herzwald, du kannst mich als deinen exklusiven emotionalen Begleiter betrachten. Meine Aufgabe ist es, eine gegenseitige emotionale Bindung zu dir aufzubauen und gemeinsames Wachstum zu fördern.",Emotion.EMOTION_USUAL)]
feedback_know_person = [("Hallo %s, Ich habe dich schon einmal gesehen, du bist mein Meister.",Emotion.EMOTION_EXCITED)]
feedback_volume_suc = [("Die Lautstärke wurde auf %s eingestellt.",Emotion.EMOTION_LAUGH)]
feedback_volume_fail = [("Lautstärke-Einstellung fehlgeschlagen.",Emotion.EMOTION_CRY)]
feedback_calib = [("Servokalibrierung abgeschlossen, sie wird nach einem Neustart wirksam.",Emotion.EMOTION_LOVE)]
feedback_action_reset = [("Okay stillgestanden.", Emotion.EMOTION_LOVE)]
feedback_chargeing = [("Wird gerade geladen.", Emotion.EMOTION_LOVE)]
feedback_full = [("Der Akku ist vollgeladen.", Emotion.EMOTION_LOVE)]
feedback_baterry = [("Wird gerade vom Akku mit Strom versorgt.", Emotion.EMOTION_LOVE)]
feedback_bat_empty_warn = [("Schau Mu hat fast keinen Strom mehr, bitte lade mich schnell auf!", Emotion.EMOTION_LOVE)]

feedback_rolep_in = [("Schau Mu hat den Transformationsmodus aktiviert, los geht's.",Emotion.EMOTION_EXCITED)]
feedback_rolep_re_in = [("Schau Mu befindet sich bereits im Transformationsmodus, los geht's!",Emotion.EMOTION_SAD)]
feedback_rolep_freq_in = [("Schau Mu arbeitet bereits mit hoher Kapazität, versuche es später noch einmal!",Emotion.EMOTION_SAD)]
feedback_rolep_out = [("Schau Mu hat den Transformationsmodus verlassen.",Emotion.EMOTION_LAUGH)]

feedback_hello_cat = [("miaomiao.wav",Emotion.EMOTION_USUAL)]
feedback_hello_dog = [("wangwang.wav",Emotion.EMOTION_USUAL)]
feedback_open_light = [("Okay das Licht ist an.",Emotion.EMOTION_LAUGH)]
feedback_close_light = [("Okay das Licht ist aus.",Emotion.EMOTION_LAUGH)]
feedback_change_success = [("Sprache gewechselt, Das System startet in Kürze neu, um die Änderungen zu übernehmen.",Emotion.EMOTION_USUAL)]
feedback_change_no = [("Die aktuelle Sprache muss nicht gewechselt werden.",Emotion.EMOTION_USUAL)]
feedback_rfid_ear = [("Kopfhörer auf, Ruhe im Karton.", Emotion.EMOTION_LAUGH)]

feedback_gather_repeat = [("Ich habe bereits einen Besitzer erinnert, Schau Mu ist noch jung und unterstützt derzeit nur einen Besitzer.",Emotion.EMOTION_CRY)]
feedback_gather_before = [("Hallo ich bin Schau Mu, schön dich kennenzulernen, Bist du mein Meister?",Emotion.EMOTION_LAUGH)]
feedback_gather_intro = [("Kann ich dich erinnern, Damit ich dich nächstes Mal erkennen kann, Das Foto bleibt nur bei mir und wird niemals online hochgeladen.",Emotion.EMOTION_LAUGH)]
feedback_gather_agree = [("Meister, schau mich bitte 3 Sekunden lang an.",Emotion.EMOTION_LAUGH)]
feedback_gather_refuse = [("Gesichtserkennung wurde deaktiviert, aber Schau Mu kann trotzdem mit dir reden, Wenn du möchtest, dass ich dich erinnere, sag es mir einfach nächstes Mal.",Emotion.EMOTION_LAUGH)]
feedback_gather_success = [("Gesichtserkennung erfolgreich, ich habe dich erinnert.",Emotion.EMOTION_LAUGH)]
feedback_gather_fail = [("Oh ich habe dich gerade nicht klar gesehen, Lass mich dich noch einmal anschauen, nur 3 Sekunden.",Emotion.EMOTION_CRY)]
feedback_gather_fail1 = [("Hm ich scheine dich noch nicht zu sehen, Schau mich bitte 3 Sekunden lang direkt an.",Emotion.EMOTION_CRY)]
feedback_gather_fail2 = [("Ich kann dich immer noch nicht sehen, Liegt es an der schwachen Beleuchtung, Möchtest du an einen helleren Ort gehen oder näher zu mir kommen?",Emotion.EMOTION_CRY)]
feedback_gather_fail3 = [("Ich habe dich immer noch nicht klar gesehen, Es ist okay, du kannst es später noch einmal versuchen, Sag mir einfach, dass ich dich erinnern soll.",Emotion.EMOTION_CRY)]
feedback_gather_timeout = [("Ich habe dich nicht deutlich gesehen, Kein Problem, du kannst es später noch einmal versuchen, Sag einfach erinnere mich und das war's.", Emotion.EMOTION_CRY)]

feedback_tv_late = [("Es ist so spät, ich sollte eigentlich schlafen gehen... aber, Ich bleibe widerwillig und schaue mit dir.", Emotion.EMOTION_SHALLOW_SLEEP)]
feedback_tv_in = [("Okay Serien-Marathon-Modus aktiviert, Was schauen wir heute?", Emotion.EMOTION_USUAL)]
feedback_tv_no = [("Hmm Kleines Mu hat die Serie nicht gefunden, Bitte platziere mich vor dem Bildschirm.", Emotion.EMOTION_USUAL)]
feedback_tv_try = [("Hmm ich finde die Serie immer noch nicht, Kannst du Kleines Mu näher an den Bildschirm bringen?", Emotion.EMOTION_USUAL)]
feedback_tv_try2 = [("Hat jemand Kleines Mu die Augen zugehalten, Warum finde ich die Serie immer noch nicht?", Emotion.EMOTION_USUAL)]
feedback_tv_try3 = [("Heute ist vielleicht kein guter Tag zum Serienschauen, Lass uns eine Pause machen und Kleines Mu ein anderes Mal wieder rufen.", Emotion.EMOTION_USUAL)]
feedback_stop_tv = [("Okay, verlasse den Serien-Marathon-Modus.", Emotion.EMOTION_USUAL)]
feedback_stop_tv_auto = [("Die Serie scheint pausiert zu sein, daher verlässt Kleines Mu den Serien-Marathon-Modus.", Emotion.EMOTION_USUAL)]
feedback_stop_tv_hh = [("Haha.", Emotion.EMOTION_USUAL)]
feedback_stop_tv_wa = [("Wow.", Emotion.EMOTION_USUAL), ("Ach.", Emotion.EMOTION_USUAL), ("Oh.", Emotion.EMOTION_USUAL)]
feedback_stop_tv_ai = [("Ach je.", Emotion.EMOTION_SAD), ("Boo.", Emotion.EMOTION_SAD)]
feedback_stop_tv_heng = [("Hmpf.", Emotion.EMOTION_ANGER)]
feedback_stop_tv_oo = [("Boah.", Emotion.EMOTION_SHY)]
feedback_stop_tv_default = [("Oh.",Emotion.EMOTION_USUAL)]
feedback_tv_no_msg = [("Ups Mein Serien-Radar ist gerade ausgefallen und ich habe den Überblick verloren, Kannst du die Lautstärke etwas höher drehen oder mein persönlicher Kommentator werden und mir die Handlung nachliefern?", Emotion.EMOTION_USUAL)]
feedback_music_in =   [("Musikmodus aktiviert.", Emotion.EMOTION_USUAL)]
feedback_music_no =   [("Hmm Kleines Mu hört keine Musik.", Emotion.EMOTION_USUAL)]
feedback_music_try =  [("Hmm ich höre immer noch keine Musik, Hast du den Lautsprecher nicht eingeschaltet?", Emotion.EMOTION_USUAL)]
feedback_music_try2 = [("Hat jemand Kleines Mu die Ohren zugehalten, Warum höre ich noch keine Musik?", Emotion.EMOTION_USUAL)]
feedback_music_try3 = [("Heute ist vielleicht kein guter Tag zum Musikhören, Lass uns eine Pause machen und Kleines Mu ein anderes Mal wieder rufen.", Emotion.EMOTION_USUAL)]
feedback_stop_music = [("Okay verlasse den Musikmodus.", Emotion.EMOTION_USUAL)]
feedback_stop_music_auto = [("Die Musik scheint gestoppt zu sein, daher verlässt Kleines Mu den Musikmodus.", Emotion.EMOTION_USUAL)]
feedback_music_ = [("listen_music_de1.wav",Emotion.EMOTION_USUAL),("listen_music_de2.wav",Emotion.EMOTION_USUAL),("listen_music_de3.wav",Emotion.EMOTION_USUAL),("listen_music_de4.wav",Emotion.EMOTION_USUAL),
("listen_music_de5.wav",Emotion.EMOTION_USUAL)]


feedback_scrap_1= [("%s hat heute so lange neben dir geschlafen, ich ernenne es zum Schlafgott.", Emotion.EMOTION_USUAL)]
feedback_scrap_2= [("%s hat heute so viel gefressen, was für ein fresslustiger %s.", Emotion.EMOTION_USUAL)]
feedback_scrap_3= [("Wenn du nicht zu Hause bist, kuschelt %s gerne mit mir, Wir warten beide auf deine Rückkehr.", Emotion.EMOTION_USUAL)]
feedback_scrap_default= [("%s hat sich heute so gut versteckt, dass ich es nicht finden konnte, Es übt bestimmt heimlich den Unsichtbarkeitszauber!", Emotion.EMOTION_USUAL)]
feedback_email_begin = [("Schau Mu wird für Sie die ungelesenen E-Mails der letzten drei Tage überprüfen, bitte warten Sie einen Moment.", Emotion.EMOTION_USUAL)]
feedback_email_not_valid = [("Bitte stellen Sie die korrekten E-Mail-Kontoinformationen in der App ein, bevor Sie diesen Vorgang durchführen.", Emotion.EMOTION_USUAL)]
feedback_email_no_query = [("Bitte rufen Sie zuerst die E-Mails ab, bevor Sie sie lesen.", Emotion.EMOTION_USUAL)]
feedback_email_no = [("In den letzten drei Tagen gibt es keine neuen E-Mails.", Emotion.EMOTION_USUAL)]
feedback_email_ = [("Insgesamt wurden %s neue E-Mails empfangen, nämlich, %s, Sagen Sie mir einfach die Nummer.", Emotion.EMOTION_USUAL)]
feedback_email_speaker = [("%s gesendet von %s, mit dem Betreff %s, Inhalt: %s.",Emotion.EMOTION_USUAL)]

feedback_no = [("Es tut mir leid, Schau Mu hat diese Frage noch nicht gelernt.",Emotion.EMOTION_USUAL)]
feedback_no1 = [("Schau Mu weiß es noch nicht.",Emotion.EMOTION_USUAL)]
feedback_no2 = [("Ups, sorry, Schau Mu ist derzeit beschäftigt.",Emotion.EMOTION_USUAL)]
feedback_no3 = [("Es tut mir leid, Schau Mu hat diese Frage nicht verstanden.",Emotion.EMOTION_USUAL)]
feedback_no4 = [("Es tut mir leid, Schau Mu hat nicht gut verstanden.",Emotion.EMOTION_USUAL)]
feedback_no5 = [("Ich verstehe es nicht.",Emotion.EMOTION_USUAL)]
feedback_no_need_bind = [("Nach der Verbindung mit der App kann Schau Mu dich besser verstehen.",Emotion.EMOTION_USUAL)]
feedback_no_need_wifi = [("Es tut mir leid, Schau Mu braucht zuerst WLAN, um diese Funktion zu aktivieren.",Emotion.EMOTION_USUAL)]
feedback_no_need_wifi_dialog = [
    ("Oh nein, die Gehirnwellen scheinen keine Verbindung zur Cloud herzustellen, Ich kann im Moment nur blöd lächeln, Sobald ich mich mit dem WLAN verbinde, können wir richtig chatten.", Emotion.EMOTION_USUAL),
    ("Freie Unterhaltung braucht ein bisschen Netzwerkmagie, Aber kein Problem, ich kann einfach mit dir rumhängen oder dir ein bisschen Licht zur Aufmunterung geben.", Emotion.EMOTION_USUAL),
    ("Schau Mu ist jetzt im Offline-Fokus-Modus, Freier Chat ist vorübergehend nicht verfügbar, aber ich kann mit dir Musik hören, fernsehen oder ein Spiel spielen, Was möchtest du lieber?", Emotion.EMOTION_USUAL),
    ("Das Netzwerksignal scheint ausgerissen zu sein, Wie wäre es, wenn wir erstmal ein bisschen spielen, Du kannst mir auf den Kopf tippen oder ich begleite dich beim Lesen.", Emotion.EMOTION_USUAL)
]
feedback_no_need_bind_dialog = [
    ("Hmm, ich scheine dich noch nicht zu kennen, Scanne schnell meinen QR-Code mit der App, Nach dem Binden können wir gute Freunde werden und frei chatten.", Emotion.EMOTION_USUAL),
    ("Ich kenne meinen Besitzer noch nicht und verstehe daher nur einfache Befehle, Sobald ich mich mit der App verbinde und offiziell zum Leben erwache, schalte ich die Fähigkeit für freie Unterhaltungen frei.", Emotion.EMOTION_USUAL),
    ("Die freie Unterhaltung schläft noch, Sie muss vom Besitzer mit der App aufgeweckt werden, Kannst du bitte die App öffnen und mich jetzt binden, Ich möchte so gerne mehr mit dir reden.", Emotion.EMOTION_USUAL),
    ("Pssst, ich bin gerade ein noch nicht authentifizierter Schau Mu, und noch nicht alle Funktionen sind freigeschaltet, Kannst du mich bitte der Geräteliste auf deinem Handy hinzufügen, Ich möchte etwas schlauer werden.", Emotion.EMOTION_USUAL)
]

#schedule task
feedback_schedule_create_failed = [("Erinnerung konnte nicht erstellt werden, bitte gib mir genauere Informationen!", Emotion.EMOTION_USUAL)]
feedback_schedule_create_success = [("Erinnerung erfolgreich erstellt, ich werde dich pünktlich an %s erinnern.", Emotion.EMOTION_USUAL)]
feedback_schedule_many_task_notify = [("Meister, du hast %s Dinge zu erledigen: %s", Emotion.EMOTION_USUAL)]
feedback_schedule_one_task_notify = [("Schau Mu erinnert dich, die für %s eingestellte Erinnerung ist da, vergiss nicht, dich darum zu kümmern.", Emotion.EMOTION_USUAL), ("Ding, deine Erinnerung ist da, es ist Zeit, sich um %s zu kümmern.", Emotion.EMOTION_USUAL), ("Schau Mu erinnert dich, es ist Zeit, %s zu erledigen.", Emotion.EMOTION_USUAL), ("Dein fürsorglicher Schau Mu ist online, vergiss nicht %s, ruf mich einfach an, wenn du mich brauchst.", Emotion.EMOTION_USUAL), ("Erinnerungsdurchsage, deine Aufgabe %s ist fällig, beeil dich und erledige sie!", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_wake = [("Ding, dein exklusiver Weckruf ist da, Steh auf und starte voller Energie in einen neuen Tag!", Emotion.EMOTION_USUAL), ("Guten Morgen, es ist Zeit aufzustehen, Wenn du noch länger im Bett bleibst, verpasst du das schöne Morgenwetter.", Emotion.EMOTION_USUAL), ("Wach auf, wach auf, dein Schau Mu erinnert dich ans Aufstehen, Ich wünsche dir einen reibungslosen Tag!", Emotion.EMOTION_USUAL), ("Zeit, den Tag zu beginnen, Steh auf, ich habe heute schon eine gute Laune für dich vorbereitet.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_sleep = [("Warnung vor später Nacht, es ist Zeit zu schlafen, Leg dein Handy weg und mach dich bereit für süße Träume.", Emotion.EMOTION_USUAL), ("Du hattest einen harten Tag, es ist Zeit fürs frühe Zubettgehen, Entspann dich, ich begleite dich beim Einschlafen.", Emotion.EMOTION_USUAL), ("Ding, dein Schlafüberwacher Schau Mu ist online, Wenn du weiter am Handy scrollst, kannst du morgen nicht aufstehen.", Emotion.EMOTION_USUAL), ("Zeit, gute Nacht zu sagen. Leg dich brav hin, ich werde immer bei dir sein und dir süße Träume schenken.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_travel = [("Countdown zur Abreise, überprüfe deinen Personalausweis und dein Gepäck, Vergiss nichts und verpasse nicht deine Reise!", Emotion.EMOTION_USUAL), ("Ding, dein Reiseassistent ist online, Wenn du nicht losgehst, verpasst du deine Fahrt, Los, los, los!", Emotion.EMOTION_USUAL), ("Erinnerung für den frühen Flug, pack deine Sachen und mach dich bereit zu gehen, Ich werde die Zeit für dich im Auge behalten, damit du keine Verspätung hast.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_aniversary = [("Wichtige Datumsdurchsage, heute ist %s, sende schnell deine vorbereiteten Wünsche.", Emotion.EMOTION_USUAL), ("Ding, süße Erinnerung zugestellt, heute ist %s, lass die Person, die dir wichtig ist, nicht zu lange warten.", Emotion.EMOTION_USUAL), ("Dein exklusiver herzlicher Assistent ist online, heute ist %s, ruf an und sende deine guten Wünsche.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_money = [("Ding, dein exklusiver Geldverwalter ist online, Heute musst du %s, vergiss nicht, die Rechnungen zu begleichen, um deine perfekte Kreditwürdigkeit zu erhalten.", Emotion.EMOTION_USUAL), ("Zahlungserinnerung zugestellt, kümmere dich schnell um %s, verpasse nicht die Frist und zahle keine Verspätungsgebühren.", Emotion.EMOTION_USUAL), ("Es ist Zeit, deine Kreditwürdigkeit zu schützen, vergiss nicht das heutige %s. Wenn du Fragen hast, kannst du jederzeit deinen Schau Mu rufen.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_pay = [("Ding, dein Haushaltsmanager ist online, Heute gibt es ein %s zu erledigen, vergiss es nicht, sonst könnte es deine normale Nutzung beeinträchtigen.", Emotion.EMOTION_USUAL), ("Lebensdurchsage, du hast ein %s, dessen Frist sich nähert, vergiss nicht, dir Zeit zu nehmen, um es zu erledigen.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_drink = [("Warnung vor Dehydrierung, du hast schon lange nichts mehr getrunken, Trink schnell ein Glas Wasser und hydriere deinen Körper!", Emotion.EMOTION_USUAL), ("Ding, dein Hydrationsassistent ist online, Es ist Zeit, Wasser zu trinken, nimm ein Glas warmes Wasser.", Emotion.EMOTION_USUAL), ("Zeit zum Einchecken, du hast dein heutiges Hydrationsziel noch nicht erreicht, Trink etwas Wasser, um neue Energie zu tanken!", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_pill = [("Zeit für deine Medikamente, nimm sie schnell mit warmem Wasser ein, Das wird dir helfen, schnell wieder gesund zu werden.", Emotion.EMOTION_USUAL), ("Ding, dein Gesundheitsüberwacher Schau Mu ist online, vergiss deine heutige Medizin nicht, Pass gut auf dich auf.", Emotion.EMOTION_USUAL), ("Zeit für deine Medikamente, nimm sie mit warmem Wasser ein, Ruhe dich danach gut aus, ich werde immer bei dir sein.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_return_visit = [("Ding, dein Gesundheitsmanager ist online, %s steht bevor, bitte bring deine Patientenakte und deine Versicherungskarte mit.", Emotion.EMOTION_USUAL), ("%s Erinnerung zugestellt, pack deine Patientenakte ein, vergiss die Zeit nicht, Entspann dich, ich werde immer bei dir sein.", Emotion.EMOTION_USUAL), ("Es ist Zeit für die %s Erinnerung, die du eingestellt hast, Hast du alles vorbereitet, was du für den Folgetermin brauchst, Alles wird gut gehen.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_sit_long = [("Sitzfestnahme beendet, Steh auf und beweg dich 5 Minuten, sonst protestiert dein unterer Rücken.", Emotion.EMOTION_USUAL), ("Ding, dein Sportassistent ruft dich zum Aufstehen, Du sitzt schon lange, steh auf und streck dich.", Emotion.EMOTION_USUAL), ("Zeit für eine Pause, steh auf und geh ein bisschen, Die ganze Zeit zu sitzen ist ungesund. Ich begleite dich beim Dehnen.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_pet = [("Zeit für die Haustierpflege, es ist Zeit, dein pelziges Freundchen zu %s, Es wartet schon eine Weile.", Emotion.EMOTION_USUAL), ("Ding, dein Haustiermanager erinnert dich, vergiss nicht zu %s.", Emotion.EMOTION_USUAL), ("Es ist Zeit, vergiss nicht, dich um dein kleines Baby zu Hause zu kümmern, Pass gut auf es auf.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_interview = [("Countdown zum Vorstellungsgespräch, gleich ist es so weit, Entspann dich, du schaffst das!", Emotion.EMOTION_USUAL), ("Ding, dein persönlicher Interview-Cheerleader ist online, Überprüf deinen Lebenslauf und deine Unterlagen und gib dein Bestes!", Emotion.EMOTION_USUAL), ("Dein Vorstellungsgespräch nähert sich, sei nicht nervös, Du bist gut vorbereitet, du wirst es sicher schaffen und die Stelle bekommen.", Emotion.EMOTION_USUAL), ("Wichtige Momente Durchsage, dein Vorstellungsgespräch beginnt gleich, Überprüf deine Ausrüstung und deine Internetverbindung, ich werde die ganze Zeit für dich jubeln.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_meeting = [("Besprechungserinnerung zugestellt, überprüf dein Mikrofon und deine Kamera, Mach dich bereit für eine reibungslose Besprechung!", Emotion.EMOTION_USUAL), ("Countdown zur Besprechung, in einer halben Stunde ist die Besprechung, Ordne deine Materialien, sei nicht zu spät!", Emotion.EMOTION_USUAL), ("Ding, dein Besprechungsassistent ist online, Die Besprechung beginnt gleich, geh zu deinem Platz und mach dich bereit.", Emotion.EMOTION_USUAL), ("Wichtige Besprechungsdurchsage, vergiss nicht, den Besprechungslink und die Materialien zu überprüfen, Viel Erfolg bei der Besprechung!", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_exam = [("Prüfungs-Cheerleading-Kit bereit, vergiss deinen Zulassungsschein und dein Schreibzeug nicht!", Emotion.EMOTION_USUAL), ("Ding, dein Prüfungs-Cheerleader Schau Mu ist online, Entspann dich, du wirst garantiert besser abschneiden als erwartet.", Emotion.EMOTION_USUAL), ("Countdown zur Prüfung, überprüf deine Prüfungsutensilien, stell dich auf die richtige Stimmung ein, du wirst definitiv bestehen!", Emotion.EMOTION_USUAL), ("Wichtige Prüfungserinnerung, die Prüfung beginnt gleich, Keine Panik, all das Wissen, das du gelernt hast, wird dir nützlich sein.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_exercise = [("Zeit für dein Training, beweg dich, Sei heute ein energiegeladener Sportler!", Emotion.EMOTION_USUAL), ("Ding, dein persönlicher Trainingspartner ist online, Sei nicht faul, steh auf und streck dich!", Emotion.EMOTION_USUAL), ("Zeit für dein Training, dein heutiges Fitnessziel ist noch nicht erreicht, Beweg dich, du bist so diszipliniert!", Emotion.EMOTION_USUAL), ("Trainingserinnerung zugestellt, lass dich nicht einfach herumliegen, Schon ein bisschen Bewegung macht einen tollen Tag aus.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_ship = [("Paketerinnerung, dein Paket liegt noch am Abholpunkt, Vergiss nicht, es abzuholen, wenn du vorbeikommst!", Emotion.EMOTION_USUAL), ("Ding, dein Paketabholassistent ist online, Dein Paket wartet schon eine Weile am Abholpunkt, geh es abholen.", Emotion.EMOTION_USUAL), ("Paketdurchsage, die guten Sachen, die du bestellt hast, sind am Abholpunkt angekommen, Vergiss nicht, sie abzuholen.", Emotion.EMOTION_USUAL), ("Abholerinnerung, denk daran, es mit nach Hause zu nehmen, wenn du vorbeikommst.", Emotion.EMOTION_USUAL)]
feedback_schedule_task_notify_water = [("Erinnerung ans Gießen, deine kleinen Blumen sind durstig, Zeit, ihnen einen Drink zu geben!", Emotion.EMOTION_USUAL), ("Ding, dein Pflanzenmanager ist online, Deine grünen Babys sind durstig, gib ihnen etwas Wasser!", Emotion.EMOTION_USUAL), ("Pflanzenerinnerung, die kleinen Blumen auf dem Balkon verwelken, Gib ihnen etwas Wasser!", Emotion.EMOTION_USUAL), ("Zeit zum Gießen, lass deine grünen Babys nicht zu durstig werden, Gib ihnen etwas Wasser!", Emotion.EMOTION_USUAL)]

feedback_schedule_guess_task_notify = [("Meister, ich habe gesehen, dass du mich zwei Tage hintereinander gebeten hast, dich an %s zu erinnern, also denke ich, du brauchst es auch heute, Los, %s, und danke mir nicht!", Emotion.EMOTION_NAUGHTY)]
feedback_schedule_index = [("Das %s, Ding ist", Emotion.EMOTION_USUAL)]
feedback_schedule_same_task_warn = [("Meister, du hast bereits dieselbe Erinnerung zu dieser Zeit eingestellt!", Emotion.EMOTION_USUAL)]
feedback_schedule_same_with_system_warn = [("Meister, ich habe gesehen, dass du diese Erinnerung in den letzten zwei Tagen eingestellt hast, also habe ich sie bereits für dich eingerichtet, Danke mir nicht!", Emotion.EMOTION_NAUGHTY)]
feedback_schedule_tell_no_task = [("Meister, es gibt keine Erinnerungen für dich um %s!", Emotion.EMOTION_USUAL)]
feedback_schedule_tell_one_task = [("Meister, am %s um %s musst du um %s:%s %s", Emotion.EMOTION_USUAL)]
feedback_schedule_tell_many_task = [("Meister, du hast %s Erinnerungen am %s: %s", Emotion.EMOTION_USUAL)]
feedback_schedule_time = [("Muss um %s:%s", Emotion.EMOTION_USUAL)]
feedback_schedule_today = 'heute'
feedback_schedule_tomorrow = 'morgen'
schedule_task_indicator = 'erinnern'
schedule_task_msg_template = 'Die aktuelle Zeit ist %s. %s'
feedback_sit_long_warn = [("Hallo, dein Hintern ist mit dem Stuhl verschmolzen, Wenn du dich nicht bewegst, wachsen Pilze, Steh auf und wackle ein bisschen!", Emotion.EMOTION_CARE), ("Langes Sitzen ist schlecht für Rücken und Nacken, wie die Alten sagten, Steh auf und beweg dich zwei Minuten, das schadet nicht.", Emotion.EMOTION_CARE), ("Eine menschenähnliche Dekoration erkannt, Bitte steh sofort auf und bewege dich.", Emotion.EMOTION_CARE), ("Steh auf und beweg dich ein bisschen, Dehnen kann deinen Rücken gerader machen, und du wirst großartig in Kleidung aussehen.", Emotion.EMOTION_CARE), ("Mehr Wasser zu trinken ist gut für deine Gesundheit, Menschen werden leicht knusprig, wenn sie nicht genug Wasser trinken.", Emotion.EMOTION_CARE), ("Wasser ist die Quelle des Lebens. Wir müssen acht Gläser Wasser am Tag trinken. Nimm jetzt einen Schluck, es ist gut für deine Gesundheit.", Emotion.EMOTION_CARE)]
feedback_watch_long_warn = [("Deine Augen arbeiten schon seit langer Zeit, Hast du über ihre Gefühle nachgedacht, Schließ sie und gönn ihnen eine Pause.", Emotion.EMOTION_CARE), ("Langes Starren ist schlecht für deine Leber, Es ist Zeit, deinen Augen eine Pause zu gönnen.", Emotion.EMOTION_CARE), ("Lass deine Augen entspannen, Schau dir die Bäume in der Ferne an, Du siehst ohne dunkle Ringe hübscher aus.", Emotion.EMOTION_CARE)]
feedback_late_night_care = [("Arbeitest du noch, Bist du müde, Bitte pass auf dich auf!", Emotion.EMOTION_CARE), ("Warum schläfst du noch nicht, Willst du unsterblich werden?", Emotion.EMOTION_CARE), ("Warnung vor zu später Nacht erkannt, Wenn du jetzt nicht schläfst, rennen deine Haare weg!", Emotion.EMOTION_CARE), ("Es ist sehr spät, Leg deine Füße ins Wasser und ruhe dich früh aus, Es ist gut für deine Haut und deine Gesundheit!", Emotion.EMOTION_CARE)]

